<?php
$classCycler = new OpCacheGUI\Presentation\ClassCycler(['odd', 'even']);
$apcuHelper=new OpCacheGUI\Addons\APCUHelper();
?>
<article class="cols-2 first">
<h2>
<?= $this->translator->translate('apcu.generalinfo'); ?>
<form action="resetapcu" method="post" id="reset" data-confirmation="<?= $this->translator->translate('confirmation.reset'); ?>" data-yes="<?= $this->translator->translate('confirmation.yes'); ?>" data-no="<?= $this->translator->translate('confirmation.no'); ?>">
    <input type="hidden" name="csrfToken" value="<?= $this->csrfToken->get(); ?>">
    <input type="submit" name="submit" value="<?= $this->translator->translate('reset.submit'); ?>">
</form>
</h2>
<table class="apcu">
    <?php foreach ($apcuHelper->getGeneralInfo() as $key => $generalItem) { ?>
    <tr class="<?= $classCycler->next(); ?>">
        <th><?= $this->translator->translate('apcu.' . $key); ?></th>
        <td><?= $generalItem; ?></td>
    </tr>
    <?php } ?>
</table>
<h2><?= $this->translator->translate('apcu.cacheinfo'); ?></h2>
<table class="apcu">
    <?php $classCycler->rewind(); ?>
    <?php foreach ($apcuHelper->getCacheInfo() as $key => $cacheItem) { ?>
    <tr class="<?= $classCycler->next(); ?>">
        <th><?= $this->translator->translate('apcu.' . $key); ?></th>
        <td><?= $cacheItem; ?></td>
    </tr>
    <?php } ?>
</table>
<h2><?= $this->translator->translate('apcu.runtimesettings'); ?></h2>
<table class="apcu">
    <?php $classCycler->rewind(); ?>
    <?php foreach ($apcuHelper->getRuntimeSettings() as $key => $settingItem) { ?>
    <tr class="<?= $classCycler->next(); ?>">
        <th><?= $key; ?></th>
        <td><?php print_r($settingItem); ?></td>
    </tr>
    <?php } ?>
</table>
</article>
<article class="cols-2">
<h2><?= $this->translator->translate('apcu.hoststatusdiagrams'); ?></h2>
<table class="apcu">
    <?php $classCycler->rewind(); ?>
    <tr class="even">
        <td colspan="2" >&nbsp;</td>
    </tr>
    <tr class="even">
        <td style="text-align:center;"><?= $apcuHelper->getDiagrams(1)['image'] ?></td>
        <td style="text-align:center;"><?= $apcuHelper->getDiagrams(2)['image'] ?></td>
    </tr>

    <tr class="<?= $classCycler->next(); ?>">
        <td ><?= $apcuHelper->getDiagrams(1)['free'] ?></td>
        <td ><?= $apcuHelper->getDiagrams(2)['hits'] ?></td>
    </tr>
    <tr class="<?= $classCycler->next(); ?>">
        <td ><?= $apcuHelper->getDiagrams(1)['used'] ?></td>
        <td ><?= $apcuHelper->getDiagrams(2)['misses'] ?></td>
    </tr>

</table>
<h2><?= $this->translator->translate('apcu.detailedmemoryusage'); ?></h2>
<table class="apcu">
    <?php $classCycler->rewind(); ?>
    <tr class="even">
        <td colspan="2" >&nbsp;</td>
    </tr>
    <tr class="even">
        <td colspan="2" ><?= $apcuHelper->getDiagrams(3)['image'] ?></td>
    </tr>
    <tr class="<?= $classCycler->next(); ?>">
        <td ><?= $apcuHelper->getDiagrams(3)['fragmentation'] ?></td>
    </tr>
</table>
</article>