<?php $apcuHelper=new OpCacheGUI\Addons\APCUHelper(); ?>

<section id="apcustatus-tabs" class="tabs">


 <div class="data-block clear">
     <h2><?= $this->translator->translate('apcu.generalinfo'); ?></h2>
    <table class="apcu">
        <?php foreach ($apcuHelper->getGeneralInfo() as $key => $generalItem) { ?>
        <tr>
            <td><?= $this->translator->translate('apcu.' . $key); ?></td>
            <td><?= $generalItem; ?></td>
        </tr>
        <?php } ?>
    </table>
    <form action="<?= $this->url->get('resetapcu'); ?>" method="post" id="reset" data-confirmation="<?= $this->translator->translate('confirmation.reset'); ?>" data-yes="<?= $this->translator->translate('confirmation.yes'); ?>" data-no="<?= $this->translator->translate('confirmation.no'); ?>">
            <input type="hidden" name="csrfToken" value="<?= $this->csrfToken->get(); ?>">
            <button type="submit" name="submit" value="<?= $this->translator->translate('reset.submit'); ?>" class="cnfbtn cnfbtn--fn js-confirm reset-btn">Reset</button>
        </form>

    <h2><?= $this->translator->translate('apcu.cacheinfo'); ?></h2>
    <table class="apcu">
        <?php foreach ($apcuHelper->getCacheInfo() as $key => $cacheItem) { ?>
        <tr>
            <td><?= $this->translator->translate('apcu.' . $key); ?></td>
            <td><?= $cacheItem; ?></td>
        </tr>
        <?php } ?>
    </table>
</div>
 <div class="data-block">
    <h2><?= $this->translator->translate('apcu.hoststatusdiagrams'); ?></h2>
    <table class="apcu">
        <tr class="even">
            <td style="text-align:center;"><?= $apcuHelper->getDiagrams(1)['image'] ?></td>
            <td style="text-align:center;"><?= $apcuHelper->getDiagrams(2)['image'] ?></td>
        </tr>

        <tr>
            <td ><?= $apcuHelper->getDiagrams(1)['free'] ?></td>
            <td ><?= $apcuHelper->getDiagrams(2)['hits'] ?></td>
        </tr>
        <tr>
            <td ><?= $apcuHelper->getDiagrams(1)['used'] ?></td>
            <td ><?= $apcuHelper->getDiagrams(2)['misses'] ?></td>
        </tr>
    </table>
    <h2><?= $this->translator->translate('apcu.detailedmemoryusage'); ?></h2>
    <table class="apcu">
        <tr class="even">
            <td colspan="2" ><?= $apcuHelper->getDiagrams(3)['image'] ?></td>
        </tr>
        <tr>
            <td ><?= $apcuHelper->getDiagrams(3)['fragmentation'] ?></td>
        </tr>
    </table>
</div>


</section>