<?php
$config = new OpCacheGUI\APCu\Configuration(ini_get_all('apcu'));
$status = new OpCacheGUI\APCu\Status($this->byteFormatter, $config, apcu_cache_info(), apcu_sma_info());
?>

<section id="apc-variables-tabs" class="tabs">
    <nav id="sub-nav">
        <ul>
            <li class="sna"><a href="#" data-tab="cached-scripts"><?= $this->translator->translate('apcu.vars.title'); ?></a></li>
        </ul>
    </nav>
    <section data-content="cached-scripts">
        <?php if (!count($status->getVariables())) { ?>
            <br />
            <p><?= $this->translator->translate('apcu.vars.empty'); ?></p>
        <?php } else { ?>
            <input type="search" name="filter" placeholder="<?= $this->translator->translate('apcu.vars.filter.placeholder'); ?>" autofocus>
            <table>
                <thead>
                    <tr>
                        <th><?= $this->translator->translate('apcu.vars.name'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.hits'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.size'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.accessed'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.modified'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.created'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.timeout'); ?></th>
                        <th><?= $this->translator->translate('apcu.vars.deleted'); ?></th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($status->getVariables() as $variable) { ?>
                        <tr>
                            <td><?= htmlspecialchars($variable['info']); ?></td>
                            <td><?= $variable['num_hits']; ?></td>
                            <td><?= $variable['mem_size']; ?></td>
                            <td><?= $variable['access_time']; ?></td>
                            <td><?= $variable['modification_time']; ?></td>
                            <td><?= $variable['creation_time']; ?></td>
                            <td><?= $variable['ttl']; ?></td>
                            <td><?= $variable['deletion_time']; ?></td>
                            <td>
                                <form action="<?= $this->url->get('invalidate'); ?>" method="post">
                                    <input type="hidden" name="csrfToken" value="<?= $this->csrfToken->get(); ?>">
                                    <input type="hidden" name="key" value="<?= 'NEEDS IDENTIFIER!'; ?>">
                                    <button type="submit" name="submit" value="Invalidate" class="cnfbtn cnfbtn--fn js-confirm inv" title="<?= $this->translator->translate('apcu.vars.invalidate'); ?>"><?= $this->translator->translate('apcu.vars.invalidate'); ?></button>
                                </form>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        <?php } ?>
    </section>
</section>
