<?php
use  OpCacheGUI\Addons\APCUHelper;


$apcuHelper=new APCUHelper();

$MYREQUEST=array();
$MYREQUEST['SCOPE']='A';
$MYREQUEST['SORT1']='H';
$MYREQUEST['SORT2']='D';
$MYREQUEST['COUNT']=20;
$MYREQUEST['OB']=2;
$MYREQUEST['SEARCH']='';
$MYREQUEST["SH"]='';
$fieldname='info';
    $fieldheading='User Entry Label';
    $fieldkey='key';

    $cols=6;
// operation constants
define('DATE_FORMAT', 'Y/m/d H:i:s');     // US

define('GRAPH_SIZE',200);                 // Image size
define('OB_HOST_STATS',1);
define('OB_USER_CACHE',2);
define('OB_VERSION_CHECK',3);
$PHP_SELF= isset($_SERVER['SCRIPT_NAME']) ? htmlentities(strip_tags($_SERVER['SCRIPT_NAME'],''), ENT_QUOTES, 'UTF-8') : '';

$MY_SELF=
    "$PHP_SELF".
    "?SCOPE=".$MYREQUEST['SCOPE'].
    "&SORT1=".$MYREQUEST['SORT1'].
    "&SORT2=".$MYREQUEST['SORT2'].
    "&COUNT=".$MYREQUEST['COUNT'];
$SELF_WO_SORT=
    "$PHP_SELF".
    "?SCOPE=".$MYREQUEST['SCOPE'].
    "&COUNT=".$MYREQUEST['COUNT'];

?>

<section id="cached-variables-tabs" class="tabs">

    <section data-content="cached-variables">

   

<?php
      echo  '<div class="info"><table id="cached" class="apcu_cachedscripts" cellspacing=0><tbody>';
                

    echo'<tr>',
        '<th >','User Entry Label'/*APCUHelper::sortheader('S',$fieldheading,  "&OB=".$MYREQUEST['OB'])*/,'</th>',
        '<th class="thin">','Hits'/*APCUHelper::sortheader('H','Hits',         "&OB=".$MYREQUEST['OB'])*/,'</th>',
        '<th class="thin">','Size'/*APCUHelper::sortheader('Z','Size',         "&OB=".$MYREQUEST['OB'])*/,'</th>',
        '<th width="120">','Last accessed'/*APCUHelper::sortheader('A','Last accessed',"&OB=".$MYREQUEST['OB'])*/,'</th>',
        '<th width="120">','Modified at'/*APCUHelper::sortheader('M','Last modified',"&OB=".$MYREQUEST['OB'])*/,'</th>',
        '<th width="120">','Created at'/*APCUHelper::sortheader('C','Created at',   "&OB=".$MYREQUEST['OB'])*/,'</th>';

    if($fieldname=='info') {
        $cols+=2;
         echo '<th class="thin">','Timeout'/*APCUHelper::sortheader('T','Timeout',"&OB=".$MYREQUEST['OB'])*/,'</th>';
    }
    echo '<th width="120">','Deleted At'/*APCUHelper::sortheader('D','Deleted at',"&OB=".$MYREQUEST['OB'])*/,'</th></tr>';

    // builds list with alpha numeric sortable keys
    //
    $list = array();

    foreach($apcuHelper->getCache()[$apcuHelper->scope_list[$MYREQUEST['SCOPE']]] as $i => $entry) {
        $entry['info']=isset($entry['info'])? $entry['info']:$entry['key'];
        $entry['access_time']=isset($entry['access_time'])?$entry['access_time']:$entry['atime'];
        $entry['deletion_time']=isset($entry['deletion_time'])?$entry['deletion_time']:$entry['dtime'];
        $entry['creation_time']=isset($entry['creation_time'])?$entry['creation_time']:$entry['ctime'];
        $entry['num_hits']=isset($entry['num_hits'])?:$entry['nhits'];
        switch($MYREQUEST['SORT1']) {
            case 'A': $k=sprintf('%015d-',$entry['access_time']);       break;
            case 'H': $k=sprintf('%015d-',$entry['num_hits']);          break;
            case 'Z': $k=sprintf('%015d-',$entry['mem_size']);          break;
            case 'M': $k=sprintf('%015d-',$entry['mtime']);             break;
            case 'C': $k=sprintf('%015d-',$entry['creation_time']);     break;
            case 'T': $k=sprintf('%015d-',$entry['ttl']);               break;
            case 'D': $k=sprintf('%015d-',$entry['deletion_time']);     break;
            case 'S': $k=$entry["info"];                                break;
        }
       
            $list[$k.$entry[$fieldname]]=$entry;
        
    }

    if ($list) {
        // sort list
        //
        switch ($MYREQUEST['SORT2']) {
            case "A":   krsort($list);  break;
            case "D":   ksort($list);   break;
        }

        // output list
        $i=0;
        foreach($list as $k => $entry) {
      if(!$MYREQUEST['SEARCH'] || preg_match($MYREQUEST['SEARCH'], $entry[$fieldname]) != 0) {
        $sh=md5($entry["info"]);
        $field_value = htmlentities(strip_tags($entry[$fieldname],''), ENT_QUOTES, 'UTF-8');




         ?>
         <tr>
         <?php
        echo  "<td class=\"td-0 directory\" data-directoryid=\"".$i."\">";
        //<a href=\"$MY_SELF&OB=",$MYREQUEST['OB'],"&SH=",$sh,"\"><span class=\"fa fa-plus\"></span>&nbsp; ";
        echo $field_value;
        //echo '</a>';
        echo '</td>';


        echo '<td class="td-n center">',APCUHelper::niceSize($entry['num_hits']),'</td>',
          '<td class="td-n right">',APCUHelper::niceSize($entry['mem_size']),'</td>',
          '<td class="td-n center">',date(DATE_FORMAT,$entry['access_time']),'</td>',
          '<td class="td-n center">',date(DATE_FORMAT,$entry['mtime']),'</td>',
          '<td class="td-n center">',date(DATE_FORMAT,$entry['creation_time']),'</td>';

        if($fieldname=='info') {
          if($entry['ttl'])
            echo '<td class="td-n center">'.$entry['ttl'].'s</td>';
          else
            echo '<td class="td-n center">None</td>';
        }
        if ($entry['deletion_time']) {

          echo '<td class="td-last center">', date(DATE_FORMAT,$entry['deletion_time']), '</td>';
        } else if ($MYREQUEST['OB'] == OB_USER_CACHE) {

          echo '<td class="td-last center">';
          echo '';//'[<a href="', $MY_SELF, '&OB=', $MYREQUEST['OB'], '&DU=', urlencode($entry[$fieldkey]), '">Delete Now</a>]';
          echo '</td>';
        } else {
          echo '<td class="td-last center"> &nbsp; </td>';
        }
        echo '</tr>';
        echo '<tr class="script" data-directoryid="'. $i.'"><td colspan="8">';

        if ($sh == $MYREQUEST["SH"]) {
            echo '<pre>'.htmlentities(print_r(apcu_fetch($entry['info']), 1)).'</pre>';
        } else {
            echo 'Here you should see the contents of the stored key';
        }

        echo '</td></tr>';
        $i++;
        if ($i == $MYREQUEST['COUNT'])
          break;
      }
        }

    } else {
        echo '<tr class=tr-0><td class="center" colspan=',$cols,'><i>No data</i></td></tr>';
    }
    echo <<< EOB
        </tbody></table>
EOB;
    ?>
   
</section>
</section>
