<?php
$config = new OpCacheGUI\APCu\Configuration(ini_get_all('apcu', false));
$status = new OpCacheGUI\APCu\Status($this->byteFormatter, $config, array_merge(apcu_cache_info(), ['version' => phpversion('apcu')]), apcu_sma_info());
?>

<section id="apcuvars-tabs" class="tabs">
    <nav id="sub-nav">
        <ul>
            <li class="sna"><a href="#" data-tab="apcu-variables"><?= $this->translator->translate('apcu.vars.tabs.cached'); ?></a></li>
            <li><a href="#" data-tab="apcu-deleted"><?= $this->translator->translate('apcu.vars.tabs.deleted'); ?></a></li>
        </ul>
    </nav>
    <section data-content="apcu-variables">
        <table>
            <thead>
                <tr>
                    <th><?= $this->translator->translate('apcu.vars.name'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.hits'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.size'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.accessed'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.modified'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.created'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.timeout'); ?></th>
                    <th><?= $this->translator->translate('apcu.vars.deleted'); ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name</td>
                    <td>10</td>
                    <td>10K</td>
                    <td>10-10-2014 12:28:53</td>
                    <td>10-10-2014 13:38:25</td>
                    <td>09-10-2014 09:00:13</td>
                    <td>31-10-2014 09:00:13</td>
                    <td>Delete me</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>10</td>
                    <td>10K</td>
                    <td>10-10-2014 12:28:53</td>
                    <td>10-10-2014 13:38:25</td>
                    <td>09-10-2014 09:00:13</td>
                    <td>31-10-2014 09:00:13</td>
                    <td>Delete me</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>10</td>
                    <td>10K</td>
                    <td>10-10-2014 12:28:53</td>
                    <td>10-10-2014 13:38:25</td>
                    <td>09-10-2014 09:00:13</td>
                    <td>31-10-2014 09:00:13</td>
                    <td>Delete me</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>10</td>
                    <td>10K</td>
                    <td>10-10-2014 12:28:53</td>
                    <td>10-10-2014 13:38:25</td>
                    <td>09-10-2014 09:00:13</td>
                    <td>31-10-2014 09:00:13</td>
                    <td>Delete me</td>
                </tr>
            </tbody>
        </table>
    </section>
</section>