<?php
$status = new OpCacheGUI\OpCache\Status($byteFormatter);
$classCycler = new OpCacheGUI\Presentation\ClassCycler(['odd', 'even']);

$directories = [];
$directorystats = [];

foreach($status->getCachedScripts() as $data) {
    $dirname = dirname($data['full_path']);
    $directories[$dirname][basename($data['full_path'])] = $data;
    if (empty($directorystats[$dirname])) {
        $directorystats[$dirname]['name'] = $dirname;
        $directorystats[$dirname]['hits'] = $data['hits'];
        $directorystats[$dirname]['memory_consumption'] = $data['memory_consumption'];
        $directorystats[$dirname]['files'] = 1;
    } else {
        $directorystats[$dirname]['hits'] += $data['hits'];
        $directorystats[$dirname]['memory_consumption'] += $data['memory_consumption'];
        $directorystats[$dirname]['files'] += 1;
    }
}
$directories = $status->sortColumn($directorystats, $directories);
?>
<article class="cols-1">
    <table id="cached">
        <tbody>
            <?php if (!count($status->getCachedScripts())) { ?>
                <tr class="<?= $classCycler->next(); ?>">
                    <td class="empty" colspan="5"><?= $translator->translate('scripts.empty'); ?></td>
                </tr>
            <?php } else { ?>
                <?php $pos = $i = 0; ?>
                  <tr>
                    <th colspan="3" class="dir-path"><h2><a href="<?= $status->sortURI('n'); ?>"><?= $translator->translate('scripts.dir_path') . $status->sortHeader('n'); ?></a></h2></th>
                    <th class="dir-mem"><h2><a href="<?= $status->sortURI('m'); ?>"><?= $translator->translate('scripts.memory_consumption') . $status->sortHeader('m'); ?></a></h2></th>
                    <th class="dir-hits"><h2><a href="<?= $status->sortURI('h'); ?>"><?= $translator->translate('scripts.hits') . $status->sortHeader('h'); ?></a></h2></th>
                    <th class="dir-files"><h2><a href="<?= $status->sortURI('f'); ?>"><?= $translator->translate('scripts.files') . $status->sortHeader('f'); ?></a></h2></th>
                  </tr>
                <?php foreach ($directories as $directory => $scripts) { ?>
                      <?php $classCycler->set_position($pos); ?>
                      <tr class="<?= $classCycler->next(); ?>">
                        <td colspan="3" class="directory" data-directoryid="<?= ++$i; ?>"><img src="style/toggle-expand.png" alt="+"><?= $directory; ?></td>
                        <td class="dir-mem"><?= $byteFormatter->format($directorystats[$directory]['memory_consumption']); ?></td>
                        <td class="dir-hits"><?= sprintf("%s", $directorystats[$directory]['hits']); ?></td>
                        <td class="dir-files"><?= sprintf("%s", $directorystats[$directory]['files']); ?></td>
                      </tr>
                      <tr class="script heading" data-directoryid="<?= $i; ?>">
                        <th class="full_path"><?= $translator->translate('scripts.full_path'); ?></th>
                        <th class="timestamp"><?= (isset($script['timestamp']) ? $translator->translate('scripts.timestamp') : ''); ?></th>
                        <th class="last_used_timestamp"><?= $translator->translate('scripts.last_used_timestamp'); ?></th>
                        <th class="memory_consumption"><?= $translator->translate('scripts.memory_consumption'); ?></th>
                        <th class="hits"><?= $translator->translate('scripts.hits'); ?></th>
                        <th class="invalidate"></th>
                      </tr>
                      <?php $pos = $classCycler->get_position(); ?>
                      <?php $classCycler->rewind(); ?>
                      <?php asort($scripts); ?> 
                      <?php foreach ($scripts as $filename => $script) { ?>
                          <tr class="script <?= $classCycler->next(); ?>" data-directoryid="<?= $i; ?>">
                            <td class="full_path"><?= $filename; ?></td>
                            <td class="timestamp"><?= isset($script['timestamp']) ? $script['timestamp'] : ''; ?></td>
                            <td class="last_used_timestamp"><?= $script['last_used_timestamp']; ?></td>
                            <td class="memory_consumption"><?= $byteFormatter->format($script['memory_consumption']); ?></td>
                            <td class="hits"><?= $script['hits']; ?></td>
                            <td class="invalidate">
                              <form id="invalidate" action="<?= isset($_GET['p']) ? '?p=invalidate' : 'invalidate'; ?>" method="post">
                                  <input type="hidden" name="csrfToken" value="<?= $csrfToken->get(); ?>">
                                  <input type="hidden" name="key" value="<?= $script['full_path']; ?>">
                                  <input type="submit" name="submit" value="<?= $translator->translate('script.invalidate'); ?>">
                                </form>
                            </td>
                          </tr>
                      <?php } ?>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
</article>
