<?php
$status = new OpCacheGUI\OpCache\Status($byteFormatter);
$classCycler = new OpCacheGUI\Presentation\ClassCycler(['odd', 'even']);

$directories = [];

foreach($status->getCachedScripts() as $data) {
    $status->populateDirectories($directories, $data);
}

$status->sortColumn($directories);
?>
<article class="cols-1">
    <table id="cached">
        <tbody>
            <?php if (!count($status->getCachedScripts())) { ?>
                <tr class="<?= $classCycler->next(); ?>">
                    <td class="empty" colspan="5"><?= $translator->translate('scripts.empty'); ?></td>
                </tr>
            <?php } else { ?>
                <?php $pos = $i = 0; ?>
                  <tr>
                    <th colspan="3" class="dir-path"><?= $status->sortAnchor('n', $translator->translate('scripts.dir_path'), 'h2'); ?></th>
                    <th class="dir-mem"><?= $status->sortAnchor('m', $translator->translate('scripts.memory_consumption'), 'h2'); ?></th>
                    <th class="dir-hits"><?= $status->sortAnchor('h', $translator->translate('scripts.hits'), 'h2'); ?></th>
                    <th class="dir-files"><?= $status->sortAnchor('f', $translator->translate('scripts.files'), 'h2'); ?></th>
                  </tr>
                  <?php foreach ($directories as $data) { ?>
                      <?php $scripts = $data['scripts']; ?>
                      <?php $data =    $data['stats']; ?>
                      <?php $classCycler->set_position($pos); ?>
                      <tr class="<?= $classCycler->next(); ?>">
                        <td colspan="3" class="directory" data-directoryid="<?= ++$i; ?>"><img src="style/toggle-expand.png" alt="+"><?= $data['name']; ?></td>
                        <td class="dir-mem"><?= $byteFormatter->format($data['memory_consumption']); ?></td>
                        <td class="dir-hits"><?= sprintf("%s", $data['hits']); ?></td>
                        <td class="dir-files"><?= sprintf("%s", $data['files']); ?></td>
                      </tr>
                      <tr class="script heading" data-directoryid="<?= $i; ?>">
                        <th class="full_path"><?= $translator->translate('scripts.full_path'); ?></th>
                        <th class="timestamp"><?= ($status->getValidTimestamp() ? $translator->translate('scripts.timestamp') : ''); ?></th>
                        <th class="last_used_timestamp"><?= $translator->translate('scripts.last_used_timestamp'); ?></th>
                        <th class="memory_consumption"><?= $translator->translate('scripts.memory_consumption'); ?></th>
                        <th class="hits"><?= $translator->translate('scripts.hits'); ?></th>
                        <th class="invalidate"></th>
                      </tr>
                      <?php $pos = $classCycler->get_position(); ?>
                      <?php $classCycler->rewind(); ?>
                      <?php ksort($scripts); ?>
                      <?php foreach ($scripts as $filename => $script) { ?>
                          <tr class="script <?= $classCycler->next(); ?>" data-directoryid="<?= $i; ?>">
                            <td class="full_path"><?= $filename; ?></td>
                            <td class="timestamp"><?= $status->getValidTimestamp() ? $script['timestamp'] : ''; ?></td>
                            <td class="last_used_timestamp"><?= $script['last_used_timestamp']; ?></td>
                            <td class="memory_consumption"><?= $byteFormatter->format($script['memory_consumption']); ?></td>
                            <td class="hits"><?= $script['hits']; ?></td>
                            <td class="invalidate">
                              <form id="invalidate" action="<?= useRW ? 'invalidate' : '?p=invalidate'; ?>" method="post">
                                  <input type="hidden" name="csrfToken" value="<?= $csrfToken->get(); ?>">
                                  <input type="hidden" name="key" value="<?= $script['full_path']; ?>">
                                  <input type="submit" name="submit" value="<?= $translator->translate('script.invalidate'); ?>">
                                </form>
                            </td>
                          </tr>
                      <?php } ?>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
</article>
