<div id="login">
   <form method="post">
       <input type="hidden" name="csrfToken" value="<?= $this->csrfToken->get(); ?>">
       <ul>
           <li><input type="text" name="username" value="<?= htmlspecialchars($this->username); ?>" placeholder="Username"></li>
           <li><input type="password" name="password" placeholder="Password"></li>
           <li><input type="submit" value="<?= $this->translator->translate('project.log_in'); ?>" disabled></li>
       </ul>
   </form>
</div>