<?php
$status      = new OpCacheGUI\OpCache\Status($byteFormatter);
$classCycler = new OpCacheGUI\Presentation\ClassCycler(['odd', 'even']);
?>

<article class="cols-3 first">
    <h2><?= $translator->translate('status.title'); ?></h2>
    <table>
        <?php foreach ($status->getStatusInfo() as $key => $statusItem) { ?>
            <tr class="<?= $classCycler->next(); ?>">
                <th><?= $translator->translate('status.' . $key); ?></th>
                <td><img src="/style/bullet-<?= $statusItem ? 'green' : 'red'; ?>-icon.png"></td>
            </tr>
        <?php } ?>
    </table>
</article>
<article class="cols-3">
    <h2><?= $translator->translate('memory.title'); ?></h2>
    <table>
        <?php $classCycler->rewind(); ?>
        <?php foreach ($status->getMemoryInfo() as $key => $memoryItem) { ?>
            <tr class="<?= $classCycler->next(); ?>">
                <th><?= $translator->translate('memory.' . $key); ?></th>
                <td><?= $memoryItem; ?></td>
            </tr>
        <?php } ?>
    </table>
</article>
<article class="cols-3">
    <h2><?= $translator->translate('stats.title'); ?></h2>
    <table>
        <?php $classCycler->rewind(); ?>
        <?php foreach ($status->getStatsInfo() as $key => $statisticItem) { ?>
            <tr class="<?= $classCycler->next(); ?>">
                <th><?= $translator->translate('stats.' . $key); ?></th>
                <td><?= $statisticItem; ?></td>
            </tr>
        <?php } ?>
    </table>
</article>
