language: php

php:
  - "5.5"
  - "5.6"

before_script:
  - pyrus install pear/PHP_CodeSniffer

script:
  - phpcs --standard=psr2 src/
  - phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
