language: php

php:
  - "7.0"
  - "7.1"
  - "nightly"

before_script:
  - composer self-update
  - composer update

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
