<?php

$texts = [
    'project.link'                                              => 'Projecte a GitHub',
    'project.log_in'                                            => 'Entrar',

    'error.not.installed.title'                                 => 'Sense instal·lar',
    'error.not.installed.description'                           => 'Sembla que OpCache no està instal·lat.',
    'error.not.enabled.title'                                   => 'Sense habilitar',
    'error.not.enabled.description'                             => 'Sembla que OpCache no està habilitat.',

    'menu.status'                                               => 'Estatus',
    'menu.config'                                               => 'Configuració',
    'menu.scripts'                                              => 'Scripts en cache',
    'menu.graphs'                                               => 'Gràfics',

    'reset.submit'                                              => 'Reiniciar',
    'confirmation.reset'                                        => 'Segur que vols esborrar la cache?',
    'confirmation.yes'                                          => 'Si',
    'confirmation.no'                                           => 'No',

    'status.title'                                              => 'Estatus',
    'status.opcache_enabled'                                    => 'Habilitat',
    'status.cache_full'                                         => 'cache plena',
    'status.restart_pending'                                    => 'Pendent de reiniciar',
    'status.restart_in_progress'                                => 'S\'està reiniciant',

    'memory.title'                                              => 'Ús de memoria',
    'memory.used_memory'                                        => 'Memòria utilitzada',
    'memory.free_memory'                                        => 'Memòria lliure',
    'memory.wasted_memory'                                      => 'Memoria usada',
    'memory.current_wasted_percentage'                          => 'Usada actualment',

    'stats.title'                                               => 'Estadístiques',
    'stats.num_cached_scripts'                                  => 'Scripts en cache',
    'stats.num_cached_keys'                                     => 'Claus en cache',
    'stats.max_cached_keys'                                     => 'Claus màximes en cache',
    'stats.hits'                                                => 'Encerts',
    'stats.start_time'                                          => 'Temps d\'inici',
    'stats.last_restart_time'                                   => 'Últim reinici',
    'stats.oom_restarts'                                        => 'Reinicis de Oom',
    'stats.hash_restarts'                                       => 'Reinicis de Hash',
    'stats.manual_restarts'                                     => 'Reinicis manuals',
    'stats.misses'                                              => 'Perduts',
    'stats.blacklist_misses'                                    => 'Llista negra de no trobats',
    'stats.blacklist_miss_ratio'                                => 'Proporció de perduts',
    'stats.opcache_hit_rate'                                    => 'Proporció d\'encerts d\'Opcache',

    'config.title'                                              => 'Configuració',
    'config.opcache.enable'                                     => 'Habilitat',
    'config.opcache.enable.description'                         => 'Determina si Zend OPCache està habilitat.',
    'config.opcache.enable_cli'                                 => 'Habilitat per CLI',
    'config.opcache.enable_cli.description'                     => 'Determina si Zend OPCache està habilitat per a la versió CLI de PHP.',
    'config.opcache.use_cwd'                                    => 'Claus del directori actual',
    'config.opcache.use_cwd.description'                        => 'Quan aquesta directiva està habilitada, OPcache agrega el directori actual a la clau de l\'script. D\'aquesta manera s\'eviten problemes de col·lisió per noms repetits. Deshabilitar aquesta opció millora el rendiment però pot afectar a les aplicacions existents.',
    'config.opcache.validate_timestamps'                        => 'Validar timestamps',
    'config.opcache.validate_timestamps.description'            => 'Quan es deshabilita, s\'ha de reiniciar el OPcache manualment o reinciar el servidor web per tal de veure els canvis en el sistema d\'arxius.',
    'config.opcache.dups_fix'                                   => 'Solucionar duplicats',
    'config.opcache.dups_fix.description'                       => '',
    'config.opcache.revalidate_path'                            => 'Revalidar la ruta',
    'config.opcache.revalidate_path.description'                => 'Activa o desactiva la recerca d\'arxius en l\'optimització include_path.',
    'config.opcache.log_verbosity_level'                        => 'Nivell de verbositat del registre',
    'config.opcache.log_verbosity_level.description'            => 'Tots els errors d\'OPcache es poden trobar al registre del servidor. Per defecte, tan sols s\'enregistren els errors crítics (nivell 0 o 1). Pots habilitar les advertències (nivell 2), missatges d\'informació (nivell 3) o de depuració (nivell 4).',
    'config.opcache.memory_consumption'                         => 'Tamany de memòria d\'Opcache',
    'config.opcache.memory_consumption.description'             => 'Tamany de la memòria compartida d\'OPcache.',
    'config.opcache.interned_strings_buffer'                    => 'Cadenes internes del buffer',
    'config.opcache.interned_strings_buffer.description'        => 'Tamany de memòria per cadenes internes en Mbytes.',
    'config.opcache.max_accelerated_files'                      => 'Màxim d\'scripts en cache',
    'config.opcache.max_accelerated_files.description'          => 'Número màxim de claus (scripts) a la taula de hash. Es permeten entre 200 i 100000 claus.',
    'config.opcache.max_wasted_percentage'                      => 'Límit d\'ús abans de reiniciar.',
    'config.opcache.max_wasted_percentage.description'          => 'Percentatge de memòria màxima a partir del qual es programarà un reinici.',
    'config.opcache.consistency_checks'                         => 'Frequència de comprovació de consistència',
    'config.opcache.consistency_checks.description'             => 'Revisar el checksum de la memòria interna N peticions. El valor per defecte "0" significa que no es revisarà mai.',
    'config.opcache.force_restart_timeout'                      => 'Forçar timeout de reinici',
    'config.opcache.force_restart_timeout.description'          => 'Temps que cal esperar (en segons) per a que es torni a iniciar si no es pot accedir a la cache.',
    'config.opcache.revalidate_freq'                            => 'Freqüència de revisió de canvis',
    'config.opcache.revalidate_freq.description'                => 'Intèrval de temps (en segons) per al qual es revisaran els timestamps dels arxius per buscar canvis a l\'asignació de la memòria compartida. "1" significa revisar cada segon, pero tan sols un cop per petició. "0" significa validar sempre.',
    'config.opcache.preferred_memory_model'                     => '',
    'config.opcache.preferred_memory_model.description'         => 'Backend de memoria compartida preferida. Deixa-ho en blanc si vols que el sistema decideixi.',
    'config.opcache.blacklist_filename'                         => 'Llista negra',
    'config.opcache.blacklist_filename.description'             => 'Ubicació de la lista negra d\'OPcache (wildcards permitidos). Cada llista negra d\'OPcache és un arxiu de text que conté els noms dels arxius que no s\'acceleraran. El format de l\'arxiu és una línea nova per cada arxiu que es vol ometre. El nom de l\'arxiu hauria de ser amb la ruta completa o tan sols el prefix de l\'arxiu (p.ex. /var/www/x posa a la llista negra tots els arxius i directoris a /var/www que comencin per \'x\'). Les líneas que comencen amb ; seran ignorades (comentaris).',
    'config.opcache.max_file_size'                              => 'Tamany màxim d\'arxiu',
    'config.opcache.max_file_size.description'                  => 'Permet excluir arxius de gran tamany a la cache. Per defecte s\'inclouen tots els arxius.',
    'config.opcache.error_log'                                  => 'Registre d\'errors',
    'config.opcache.error_log.description'                      => 'Nom de l\'arxiu error_log d\'OPcachefile. En blanc s\'asignarà a "stderr".',
    'config.opcache.protect_memory'                             => 'Protegir memòria',
    'config.opcache.protect_memory.description'                 => 'Protegir la memòria compartida d\'esciptures inesperades durant l\'ejecució dels scripts. Tan sols és útil per a depuració interna.',
    'config.opcache.save_comments'                              => 'Guardar comentaris',
    'config.opcache.save_comments.description'                  => 'Quan està deshabilitat tots els comentaris de PHPDoc s\'eliminen per reduïr el tamany del codi optimitzat.',
    'config.opcache.fast_shutdown'                              => 'Tancament ràpid',
    'config.opcache.fast_shutdown.description'                  => 'Si està habilitat, s\'utilitzarà una seqüencia de tancament ràpid per tal d\'accelerar el codi.',
    'config.opcache.enable_file_override'                       => 'Sobreescriure arxius',
    'config.opcache.enable_file_override.description'           => 'Permet sobreescriure els arxius existents (file_exists, etc).',
    'config.opcache.optimization_level'                         => 'Nivell d\'optimització',
    'config.opcache.optimization_level.description'             => 'És una màscara de bits on cada bit habilita o deshabilita el pas apropiat d\'OPcache.',
    'config.opcache.mmap_base'                                  => 'Mmap base',
    'config.opcache.mmap_base.description'                      => 'The base used for shared memory segments on Windows. All PHP processes have to map shared memory into the same address space. Using this directive allows "Unable to reattach to base address" errors to be fixed.',
    'config.opcache.restrict_api'                               => 'Restrict API',
    'config.opcache.restrict_api.description'                   => 'Allows calling OPcache API functions only from PHP scripts which path is started from specified string. The default "" means no restriction.',
    'config.opcache.file_update_protection'                     => 'File update protection',
    'config.opcache.file_update_protection.description'         => 'Prevents caching files that are less than this number of seconds old. It protects from caching of incompletely updated files. In case all file updates on your site are atomic, you may increase performance by setting it to "0".',
    'config.opcache.huge_code_pages'                            => 'Huge code pages',
    'config.opcache.huge_code_pages.description'                => 'Enables or disables copying of PHP code (text segment) into HUGE PAGES. This should improve performance, but requires appropriate OS configuration.',
    'config.opcache.lockfile_path'                              => 'Lockfile path',
    'config.opcache.lockfile_path.description'                  => 'Absolute path used to store shared lockfiles (for *nix only)',
    'config.opcache.file_cache'                                 => 'File cache',
    'config.opcache.file_cache.description'                     => 'Enables and sets the second level cache directory. It should improve performance when SHM memory is full, at server restart or SHM reset. The default "" disables file based caching.',
    'config.opcache.file_cache_only'                            => 'File cache only',
    'config.opcache.file_cache_only.description'                => 'Enables or disables opcode caching in shared memory.',
    'config.opcache.file_cache_consistency_checks'              => 'File cache consistency checks',
    'config.opcache.file_cache_consistency_checks.description'  => 'Enables or disables checksum validation when script loaded from file cache.',
    'config.opcache.file_cache_fallback'                        => 'File cache fallback',
    'config.opcache.file_cache_fallback.description'            => 'Implies opcache.file_cache_only=1 for a certain process that failed to reattach to the shared memory (for Windows only). Explicitly enabled file cache is required.',
    'config.opcache.validate_permission'                        => 'Validate permission',
    'config.opcache.validate_permission.description'            => 'Validates the cached file permissions against the current user.',
    'config.opcache.validate_root'                              => 'Validate root',
    'config.opcache.validate_root.description'                  => 'Prevents name collisions in chroot\'ed environments. This should be enabled in all chroot\'ed environments to prevent access to files outside the chroot.',

    'blacklist.title'                                           => 'Llista negra',
    'blacklist.empty'                                           => 'La llista negra està buida.',

    'scripts.title'                                             => 'Scripts en cache',
    'scripts.overview.title'                                    => 'Resum',
    'scripts.empty'                                             => 'No hi ha cap script a la cache',
    'scripts.directory.script_count'                            => ' (<i class="count">%s</i> arxius)',
    'scripts.full_path'                                         => 'Nom de l\'arxiu',
    'scripts.hits'                                              => 'Encerts',
    'scripts.memory_consumption'                                => 'Memòria',
    'scripts.last_used_timestamp'                               => 'Utilitzat per últim cop',
    'scripts.timestamp'                                         => 'Creat',
    'scripts.actions'                                           => 'Accions',
    'script.invalidate'                                         => 'Invalidar',
    'scripts.filter.placeholder'                                => 'Filtrar scripts en cache',

    'graph.title'                                               => 'Gràfics',
    'graph.memory.title'                                        => 'Memòria',
    'graph.memory.free'                                         => 'lliure',
    'graph.memory.used'                                         => 'usada',
    'graph.memory.wasted'                                       => 'consumida',
    'graph.keys.title'                                          => 'Claus',
    'graph.keys.free'                                           => 'lliures',
    'graph.keys.scripts'                                        => 'usades',
    'graph.keys.wasted'                                         => 'consumides',
    'graph.hits.title'                                          => 'Encerts',
    'graph.hits.hits'                                           => 'encerts',
    'graph.hits.misses'                                         => 'perduts',
    'graph.hits.blacklist'                                      => 'llista negra'
];
