<?php

$texts = [
    'project.link'                                             => 'Projekt på GitHub',
    'project.log_in'                                           => 'Luk mig ind',

    'error.not.installed.title'                                => 'Ikke installeret',
    'error.not.installed.description'                          => 'Det ser ud til at OpCache ikke er installeret.',
    'error.not.enabled.title'                                  => 'Ikke aktiveret',
    'error.not.enabled.description'                            => 'Det ser ud til at OpCache ikke er aktiveret.',

    'menu.status'                                              => 'Status',
    'menu.config'                                              => 'Konfiguration',
    'menu.scripts'                                             => 'Cached Scripts',
    'menu.graphs'                                              => 'Grafer',

    'reset.submit'                                             => 'Nulstil',
    'confirmation.reset'                                       => 'Er du sikker på du gerne vil nulstille cachen?',
    'confirmation.yes'                                         => 'Ja',
    'confirmation.no'                                          => 'Nej',

    'status.title'                                             => 'Status',
    'status.opcache_enabled'                                   => 'Aktiveret',
    'status.cache_full'                                        => 'Cache fuld',
    'status.restart_pending'                                   => 'Genstart er verserende',
    'status.restart_in_progress'                               => 'Genstart er undervejs',

    'memory.title'                                             => 'Hukommelsesforbrug',
    'memory.used_memory'                                       => 'Brugt hukommelse',
    'memory.free_memory'                                       => 'Fri hukommelse',
    'memory.wasted_memory'                                     => 'Spildt hukommelse',
    'memory.current_wasted_percentage'                         => 'Spildt hukommelse lige nu',

    'stats.title'                                              => 'Statistik',
    'stats.num_cached_scripts'                                 => 'Cachede Scripts',
    'stats.num_cached_keys'                                    => 'Cachede nøgler',
    'stats.max_cached_keys'                                    => 'Max cachede nøgler',
    'stats.hits'                                               => 'Hits',
    'stats.start_time'                                         => 'Start tid',
    'stats.last_restart_time'                                  => 'Sidste genstart',
    'stats.oom_restarts'                                       => 'Oom genstart',
    'stats.hash_restarts'                                      => 'Hash genstart',
    'stats.manual_restarts'                                    => 'Manuelle genstart',
    'stats.misses'                                             => 'Missere',
    'stats.blacklist_misses'                                   => 'Blackliste missere',
    'stats.blacklist_miss_ratio'                               => 'Miss ratio',
    'stats.opcache_hit_rate'                                   => 'Opcache hit rate',

    'config.title'                                             => 'Konfiguration',
    'config.opcache.enable'                                    => 'Aktiveret',
    'config.opcache.enable.description'                        => 'Bestemmer hvorvidt Zend OPCache er aktiveret.',
    'config.opcache.enable_cli'                                => 'Aktiveret for CLI',
    'config.opcache.enable_cli.description'                    => 'Bestemmer hvorvidt Zend OPCache er aktiveret for CLI versionen af PHP.',
    'config.opcache.use_cwd'                                   => 'Nøgler baseret på nuværende arbejdsmappe.',
    'config.opcache.use_cwd.description'                       => 'Når dette direktiv er aktiveret, føjer OPcache den nuværende arbejdsmappe til script nøglen, dermed fjernes eventuelle kollisioner mellem filer med samme navn (basenavn). Deaktivering af direktivet forbedrer ydeevenen, men kan knække eksisterende applikationer.',
    'config.opcache.validate_timestamps'                       => 'Godkend tidsstempler',
    'config.opcache.validate_timestamps.description'           => 'Hvis deaktiveret, skal du manuelt nulstille eller genstarte webserveren før ændringer i filsystemet træder i kraft.',
    'config.opcache.dups_fix'                                  => 'Dups fix',
    'config.opcache.dups_fix.description'                      => '',
    'config.opcache.revalidate_path'                           => 'Revalider sti',
    'config.opcache.revalidate_path.description'               => 'Aktiverer eller deaktiverer fil søgning i include_path optimering.',
    'config.opcache.log_verbosity_level'                       => 'Log informationsniveau',
    'config.opcache.log_verbosity_level.description'           => 'Alle OPcache fejl sendes til webserverens log. Som udgangspunkt er det kun fatale fejl (niveau 0) eller fejl (niveau 1) som logges. Du kan også aktivere advarsler (niveau 2), info-meddelelser (niveau 3) elle debug beskeder (niveau 4).',
    'config.opcache.memory_consumption'                        => 'Opcache hukommelses størrelse',
    'config.opcache.memory_consumption.description'            => 'Størrelsen af OPcache delt hukommelseslager.',
    'config.opcache.interned_strings_buffer'                   => 'Interned strings buffer',
    'config.opcache.interned_strings_buffer.description'       => 'Størrelsen af hukommelse for interned strings i Mbytes.',
    'config.opcache.max_accelerated_files'                     => 'Maksimalt cachede scripts',
    'config.opcache.max_accelerated_files.description'         => 'Det maksimale antal nøgler (scripts) i OPcache hash tabellen. Kun tal mellem 200 og 100000 er gyldige.',
    'config.opcache.max_wasted_percentage'                     => 'Maksimal spild før genstart',
    'config.opcache.max_wasted_percentage.description'         => 'Den maksimale tilladte procent af "spildt" hukommelsen, før en genstart bliver planlagt.',
    'config.opcache.consistency_checks'                        => 'Frekvens for overensstemmelseskontrol',
    'config.opcache.consistency_checks.description'            => 'Kontroller cache checksum med hvert N anmodninger. Standardværdien "0" betyder, at kontrollen er deaktiveret.',
    'config.opcache.force_restart_timeout'                     => 'Timeout på tvunget genstart',
    'config.opcache.force_restart_timeout.description'         => 'Tid at vente (i sekunder) for at en planlagt genstart begynder såfremt cachen ikke bliver tilgået.',
    'config.opcache.revalidate_freq'                           => 'Kontrolfrekvens for ændringer',
    'config.opcache.revalidate_freq.description'               => 'Hvor ofte (i sekunder) der kontrolleres fil tidsstempler for ændringer af den delte hukommelses opbevaring. "1" betyder en gang i sekunder, dog kun en gang per anmodning. "0" betyder altid valider.',
    'config.opcache.preferred_memory_model'                    => '',
    'config.opcache.preferred_memory_model.description'        => 'Foretruken delt hukommelse backend. Efterlad tom og lad systemet bestemme.',
    'config.opcache.blacklist_filename'                        => 'Blacklist',
    'config.opcache.blacklist_filename.description'            => 'Placeringen af OPcaches blackliste fil (wildcards tilladt). Hver OPcache blackliste fil er en tekstfil som indeholder navne på filer der ikke skal accelereres. Formatteringen af filen er at tilføje hvert filnavn skal tilføje på en ny linje. Filnavnet kan være med fuld sti eller blot filens præfiks (dvs. /var/www/x blacklister alle filer og mapper i /var/www som starter med \'x\'). Linjer som starter med ; bliver ignoreret (udkommentering).',
    'config.opcache.max_file_size'                             => 'Udeluk caching over størrelse',
    'config.opcache.max_file_size.description'                 => 'Tillader udelukkelse af store filer fra at blive cached. Som udgangspunkt bliver alle  filer cached.',
    'config.opcache.error_log'                                 => 'Fejl log',
    'config.opcache.error_log.description'                     => 'OPcache error_log fil navn. Ved en tom string antages "stderr".',
    'config.opcache.protect_memory'                            => 'Beskyt hukommelse',
    'config.opcache.protect_memory.description'                => 'Beskyt delt hukommelse fra uventet skrivning under udførsel af script. Kun nyttigt ved intern debugging.',
    'config.opcache.save_comments'                             => 'Gem kommentarer',
    'config.opcache.save_comments.description'                 => 'Hvis deaktiveret, er alle PHPDoc kommentar fjernet fra koden for at reducere størrelsen af den optimerede kode.',
    'config.opcache.fast_shutdown'                             => 'Hurtig lukning',
    'config.opcache.fast_shutdown.description'                 => 'Hvis aktiveret, bruges en hurtig nedluknings sekvens for accelereret kode.',
    'config.opcache.enable_file_override'                      => 'Fil tilsidesættelse',
    'config.opcache.enable_file_override.description'          => 'Tillad fil eksistens tilsidesættelse (file_exists, osv.) ydeevne funktion.',
    'config.opcache.optimization_level'                        => 'Optimering niveau',
    'config.opcache.optimization_level.description'            => 'En bitmaske, hvor hvert bit aktiverer eller deaktiverer relevante OPcache passes.',
    'config.opcache.mmap_base'                                 => 'Mmap base',
    'config.opcache.mmap_base.description'                     => 'The base used for shared memory segments on Windows. All PHP processes have to map shared memory into the same address space. Using this directive allows "Unable to reattach to base address" errors to be fixed.',
    'config.opcache.restrict_api'                              => 'Restrict API',
    'config.opcache.restrict_api.description'                  => 'Allows calling OPcache API functions only from PHP scripts which path is started from specified string. The default "" means no restriction.',
    'config.opcache.file_update_protection'                    => 'File update protection',
    'config.opcache.file_update_protection.description'        => 'Prevents caching files that are less than this number of seconds old. It protects from caching of incompletely updated files. In case all file updates on your site are atomic, you may increase performance by setting it to "0".',
    'config.opcache.huge_code_pages'                           => 'Huge code pages',
    'config.opcache.huge_code_pages.description'               => 'Enables or disables copying of PHP code (text segment) into HUGE PAGES. This should improve performance, but requires appropriate OS configuration.',
    'config.opcache.lockfile_path'                             => 'Lockfile path',
    'config.opcache.lockfile_path.description'                 => 'Absolute path used to store shared lockfiles (for *nix only)',
    'config.opcache.file_cache'                                => 'File cache',
    'config.opcache.file_cache.description'                    => 'Enables and sets the second level cache directory. It should improve performance when SHM memory is full, at server restart or SHM reset. The default "" disables file based caching.',
    'config.opcache.file_cache_only'                           => 'Fil cache kun',
    'config.opcache.file_cache_only.description'               => 'Aktiverer eller deaktiverer opcode caching i den delte hukommelse.',
    'config.opcache.file_cache_consistency_checks'             => 'Fil cache konsistens tjeks',
    'config.opcache.file_cache_consistency_checks.description' => 'Aktiverer eller deaktiverer checksumvalidering, når script hentes fra fil cachen.',
    'config.opcache.file_cache_fallback'                       => 'fil cache fallback',
    'config.opcache.file_cache_fallback.description'           => 'Indikerer opcache.file_cache_only = 1 for en bestemt proces der har fejlet genhæfte sig til den delte hukommelse (Windows kun). Eksplicit aktiveret filcache er påkrævet.',
    'config.opcache.validate_permission'                       => 'Valider tilladelse',
    'config.opcache.validate_permission.description'           => 'Validerer den cachelagrede fil tilladelser mod den nuværende bruger.',
    'config.opcache.validate_root'                             => 'Validér rod',
    'config.opcache.validate_root.description'                 => 'Forhindrer navne kollisioner i chroot\'ed miljøer. Dette bør aktiveres i alle chroot\'ed miljøer for at forhindre adgang til filer uden for chrooten.',
  
    'blacklist.title'                                          => 'Blacklist',
    'blacklist.empty'                                          => 'Ingen scripts er blacklisted',

    'scripts.title'                                            => 'Cachede Scripts',
    'scripts.overview.title'                                   => 'Overblik',
    'scripts.empty'                                            => 'Ingen scripts er cached',
    'scripts.directory.script_count'                           => ' (<i class="count">%s</i> filer)',
    'scripts.full_path'                                        => 'Filnavn',
    'scripts.hits'                                             => 'Hits',
    'scripts.memory_consumption'                               => 'Hukommelse',
    'scripts.last_used_timestamp'                              => 'Senest brugt',
    'scripts.timestamp'                                        => 'Oprettet',
    'scripts.actions'                                          => 'Handlinger',
    'script.invalidate'                                        => 'Ugyldiggøre',
    'scripts.filter.placeholder'                               => 'Filtrer cachede scripts',

    'graph.title'                                              => 'Grafer',
    'graph.memory.title'                                       => 'Hukommelse',
    'graph.memory.free'                                        => 'Fri',
    'graph.memory.used'                                        => 'brugt',
    'graph.memory.wasted'                                      => 'spildt',
    'graph.keys.title'                                         => 'Nøgler',
    'graph.keys.free'                                          => 'fri',
    'graph.keys.scripts'                                       => 'brugt',
    'graph.keys.wasted'                                        => 'spildt',
    'graph.hits.title'                                         => 'Hits',
    'graph.hits.hits'                                          => 'hits',
    'graph.hits.misses'                                        => 'missere',
    'graph.hits.blacklist'                                     => 'blacklist'
];
