<?php

$texts = [
    'project.link'                                          => 'Proyecto en GitHub',
    'project.log_in'                                        => 'Entrar',

    'error.not.installed.title'                             => 'Sin instalar',
    'error.not.installed.description'                       => 'Parece que OpCache no está instalado.',
    'error.not.enabled.title'                               => 'Sin habilitar',
    'error.not.enabled.description'                         => 'Parece que OpCache no está habilitado.',

    'menu.status'                                           => 'Estatus',
    'menu.config'                                           => 'Configuración',
    'menu.scripts'                                          => 'Scripts en caché',
    'menu.graphs'                                           => 'Gráficos',

    'reset.submit'                                          => 'Reiniciar',
    'confirmation.reset'                                    => 'Está seguro de borrar el caché?',
    'confirmation.yes'                                      => 'Sí',
    'confirmation.no'                                       => 'No',

    'status.title'                                          => 'Estatus',
    'status.opcache_enabled'                                => 'Habilitado',
    'status.cache_full'                                     => 'Caché lleno',
    'status.restart_pending'                                => 'Reiniciar pendientes',
    'status.restart_in_progress'                            => 'Reiniciar en progreso',

    'memory.title'                                          => 'Uso de memoria',
    'memory.used_memory'                                    => 'Memoria utilizada',
    'memory.free_memory'                                    => 'Memoria libre',
    'memory.wasted_memory'                                  => 'Memoria gastada',
    'memory.current_wasted_percentage'                      => 'Gastada actualmente',

    'stats.title'                                           => 'Estadísticas',
    'stats.num_cached_scripts'                              => 'Scripts en caché',
    'stats.num_cached_keys'                                 => 'Llaves en caché',
    'stats.max_cached_keys'                                 => 'Máximas llaves en caché',
    'stats.hits'                                            => 'Aciertos',
    'stats.start_time'                                      => 'Tiempo de inicio',
    'stats.last_restart_time'                               => 'Último reinicio',
    'stats.oom_restarts'                                    => 'Reinicio de Oom',
    'stats.hash_restarts'                                   => 'Reinicio de Hash',
    'stats.manual_restarts'                                 => 'Reinicios manuales',
    'stats.misses'                                          => 'Desaciertos',
    'stats.blacklist_misses'                                => 'Desaciertos de lista negra',
    'stats.blacklist_miss_ratio'                            => 'Proporción de desaciertos',
    'stats.opcache_hit_rate'                                => 'Proporción de aciertos de Opcache',

    'config.title'                                          => 'Configuración',
    'config.opcache.enable'                                 => 'Habilitado',
    'config.opcache.enable.description'                     => 'Determina si Zend OPCache está habilitado.',
    'config.opcache.enable_cli'                             => 'Habilitado para CLI',
    'config.opcache.enable_cli.description'                 => 'Determina si Zend OPCache está habilitado para la versión CLI de PHP.',
    'config.opcache.use_cwd'                                => 'Llaves basadas en directorio actual',
    'config.opcache.use_cwd.description'                    => 'Cuando esta directiva está habilitada, OPcache agrega el directorio actual a la llave del script,eliminando asi posibles problemas por nombres repetidos. El deshabilitar esta opción mejora el rendimiento pero puede afectar aplicaciones existentes.',
    'config.opcache.validate_timestamps'                    => 'Validar timestamps',
    'config.opcache.validate_timestamps.description'        => 'Cuando se deshabilita, debe reiniciar el OPcache manualmente o reiniciar el webserver para ver los cambios en el sistema de archivos',
    'config.opcache.inherited_hack'                         => 'Hack heredado',
    'config.opcache.inherited_hack.description'             => '',
    'config.opcache.dups_fix'                               => 'Arreglo de Dups',
    'config.opcache.dups_fix.description'                   => '',
    'config.opcache.revalidate_path'                        => 'Revalidar ruta',
    'config.opcache.revalidate_path.description'            => 'Habilita la búsqueda de archivos en la optimización de include_path.',
    'config.opcache.log_verbosity_level'                    => 'Registra nivel de verbosidad',
    'config.opcache.log_verbosity_level.description'        => 'Todos los errores de OPcache van al registro del servidor web. Por default, solo los errores (nivel 0 o 1) son registrados. Usted puede habilitar las advertencias (nivel 2), mensages de información (nivel 3) o de debuggeo (nivel 4).',
    'config.opcache.memory_consumption'                     => 'Tamaño de memoria de Opcache',
    'config.opcache.memory_consumption.description'         => 'El tamaño de la memoria compartida de OPcache.',
    'config.opcache.interned_strings_buffer'                => 'Cadenas de buffer internadas',
    'config.opcache.interned_strings_buffer.description'    => 'El tamaño de memoria para cadenas internadas en Mbytes.',
    'config.opcache.max_accelerated_files'                  => 'Maximum cached scripts',
    'config.opcache.max_accelerated_files.description'      => 'El número máximo de llaves (scripts) en la tabla de hash The maximum number of keys (scripts) in the OPcache hash table. Only numbers between 200 and 100000 are allowed.',
    'config.opcache.max_wasted_percentage'                  => 'Máximo gastado antes de reiniciar.',
    'config.opcache.max_wasted_percentage.description'      => 'El porcentaje máximo de memoria gastada hasta que se agenda un reinicio.',
    'config.opcache.consistency_checks'                     => 'Frecuencia de chequeos de consistencia',
    'config.opcache.consistency_checks.description'         => 'Revisa el checksum del cache cada N periciones. El valor por default "0" significa que estos chequeos están deshabilitados',
    'config.opcache.force_restart_timeout'                  => 'Obligar timeout de reinicio',
    'config.opcache.force_restart_timeout.description'      => 'Qué tanto esperar (en segundos) para que el reinicio agendado empiece si el caché no está siendo accedido.',
    'config.opcache.revalidate_freq'                        => 'Frecuencia para revisión de cambios',
    'config.opcache.revalidate_freq.description'            => 'Cada cuánto (en seguntos) revisa los timestamps de los archivos por cambios en la asignación de la memoria compartida. "1" significa revisar cada segundo pero sólo una vez por petición. "0" significa siempre validar.',
    'config.opcache.preferred_memory_model'                 => '',
    'config.opcache.preferred_memory_model.description'     => 'Backend de memoria compartida preferida. Dejar vacío si quiere que el sistema decida.',
    'config.opcache.blacklist_filename'                     => 'Lista negra',
    'config.opcache.blacklist_filename.description'         => 'La ubicación de la lista negra de OPcache (wildcards permitidos). Cada lista negra de OPcache es un archivo de texto que contiene los nombres de los archivos que no deben ser acelerados. El formato del archivo es agregar cada nombre de archivo en una nueva línea. El nombre del archivo puede ser la ubicación completa o solo el prefijo del archivo (ej., /var/www/x  pone en la lista negra todos los archivos y directorios en /var/www que empiezan con \'x\'). Las líneas que empiezan con ; son ignoradas (comentarios).',
    'config.opcache.max_file_size'                          => 'Excluir caché de tamaño mayor',
    'config.opcache.max_file_size.description'              => 'Permite excluir archivos grandes del caché. Por default todos los archivos se incluyen.',
    'config.opcache.error_log'                              => 'Registro de errores',
    'config.opcache.error_log.description'                  => 'El nombre del error_log de OPcachefile. Las cadenas vacías suponen "stderr".',
    'config.opcache.protect_memory'                         => 'Proteger memoria',
    'config.opcache.protect_memory.description'             => 'Proteger la memoria compartida de escituras inesperadas durante la ejecución de los scripts. Útil para debuggeo interno únicamente.',
    'config.opcache.save_comments'                          => 'Guardar comentarios',
    'config.opcache.save_comments.description'              => 'Si está deshabilitado, todos los comentarios de PHPDoc son eliminados del código para reducir el tamaño del código optimizado.',
    'config.opcache.load_comments'                          => 'Cargar comentarios',
    'config.opcache.load_comments.description'              => 'Si está deshabilitado, los comentarios de PHPDoc comments no son cargados de SHM, asi que los "Doc Comments" pueden ser siempre guardados (save_comments=1), pero no cargados por las aplicaciones que no los necesitan.',
    'config.opcache.fast_shutdown'                          => 'Cierre rápido',
    'config.opcache.fast_shutdown.description'              => 'Si está habilitado, una secuencia de apagar rápido es usada para acelerar el código.',
    'config.opcache.enable_file_override'                   => 'Sobreescribir el archivo',
    'config.opcache.enable_file_override.description'       => 'Permite sobreescribir la existencia de archivos (file_exists, etc.).',
    'config.opcache.optimization_level'                     => 'Nivel de optimización',
    'config.opcache.optimization_level.description'         => 'Es una máscara de bits donde cada bit habilita o deshabilita los pases de OPcache.',

    'blacklist.title'                                       => 'Lista negra',
    'blacklist.empty'                                       => 'La lista negra está vacía.',

    'scripts.title'                                         => 'Scripts en caché',
    'scripts.overview.title'                                => 'Resumen',
    'scripts.empty'                                         => 'Ningún script está en caché',
    'scripts.directory.script_count'                        => ' (<i class="count">%s</i> archivos)',
    'scripts.full_path'                                     => 'Nombre del archivo',
    'scripts.hits'                                          => 'Aciertos',
    'scripts.memory_consumption'                            => 'Memoria',
    'scripts.last_used_timestamp'                           => 'Último usado',
    'scripts.timestamp'                                     => 'Creado',
    'scripts.actions'                                       => 'Acciones',
    'script.invalidate'                                     => 'Invalidar',
    'scripts.filter.placeholder'                            => 'Filtrar scripts en caché',

    'graph.title'                                           => 'Gráficos',
    'graph.memory.title'                                    => 'Memoria',
    'graph.memory.free'                                     => 'libre',
    'graph.memory.used'                                     => 'usada',
    'graph.memory.wasted'                                   => 'gastada',
    'graph.keys.title'                                      => 'Llaves',
    'graph.keys.free'                                       => 'libres',
    'graph.keys.scripts'                                    => 'usadas',
    'graph.keys.wasted'                                     => 'gastadas',
    'graph.hits.title'                                      => 'Aciertos',
    'graph.hits.hits'                                       => 'aciertos',
    'graph.hits.misses'                                     => 'desaciertos',
    'graph.hits.blacklist'                                  => 'lista negra',

    'menu.apcustatus'                                       => 'Status de APCU',
    'apcu.status.title'                                     => 'Status de APCU',
    'menu.apcuconfig'                                       => 'Parámetros de APCU',
    'apcu.config.title'                                     => 'Parámetros de APCU',
    'menu.apcuvars'                                         => 'Variables de APCU',
    'apcu.vars.title'                                       => 'Variables de APCU',

    'apcu.status' => 'Estatus APCu',
    'apcu.generalinfo' => 'Información General APCu',
    'apcu.apcversion' => 'Versión APCu',
    'apcu.phpversion' => 'Versión PHP',
    'apcu.server_name' => 'Servidor APCu',
    'apcu.server_software' => 'Software de Servidor',
    'apcu.sharedmemory' => 'Memoria Compartida',
    'apcu.start_time' => 'Fecha Inicio',
    'apcu.uptime' => 'Tiempo en línea',
    'apcu.file_upload_progress' => 'Soporte para carga de archivos',

    'apcu.cacheinfo' => 'Información de Caché APCu',
    'apcu.cached_vars'=> 'Variables en Caché',
    'apcu.num_hits'=> 'Aciertos',
    'apcu.num_misses'=> 'Desaciertos',
    'apcu.req_rate_user'=> 'Tasa de peticiones (aciertos, desaciertos)',
    'apcu.hit_rate_user'=> 'Tasa de Aciertos',
    'apcu.miss_rate_user'=> 'Tasa de Desaciertos',
    'apcu.insert_rate_user'=> 'Tasa de inserciones',
    'apcu.num_expunges'=> 'Conteo total de Caché',

    'apcu.apcuconfig' => 'Configuración de Tiempo de Ejecución de APCu',
    'apcu.runtimesettings' => 'Configuración de Tiempo de Ejecución de APCu',
    
    'apcu.hoststatusdiagrams'=>'Diagramas de Estado de Servidor APCu',
    'apcu.detailedmemoryusage'=>'Uso detallado de memoria y fragmentación APCu',


    'apc.enabled' => 'apc.enabled si se deja en 0 se deshabilita APCu. Sirve para apagar APCu cuando se ha compilado estáticamente. Si está compilado como librería de PHP, basta comentar la línea donde se le incluye',
    'apc.enable_cli' => 'Más que nada para probar y debuggear, ya que esto habilita el APCu para PHP en línea de comando, En circunstancias normales no tiene sentido crear o destruir variables de caché entre ejecuciones de línea de comando, pero para casos especiales es bueno poder habilitarlo.',
    'apc.coredump_unmap' => 'Permite que APCu maneje señales del sistema operativo como SIGSEGV, que escribe archivos del núcleo cuando se emite. Al recibir la señal, APCu intentará deshacer el segmento de memoria mapeada, para excluirlos del dump. Esta configuración podría mejorar la estabilidad del server cuando se mata el proceso y hay mucha memoria destinada a APCu.',
    'apc.entries_hint' => 'Es una sugerencia respecto a cuantas variables se deben almacenar. Dejarlo en cero para no usar sugerencia.',
    'apc.gc_ttl' => 'Cuántos segundos permanece una entrada de caché en la lista de recolección de basura. Sirve como respaldo en caso de que el server se caiga mientras ejecuta un archivo de caché. Si ese archivo se modifica, la memoria destinada a resguardar la versión previa de ese archivo no se va a liberar hasta cumplir tantos segundos como dice este setting. Si se deja en cero, no se usa.',
    'apc.mmap_file_mask' => 'Cuando APCu se compiló co soporte MMAP usando --enable-mmap, esta es la máscara de archivos que se para al módulo mmap para saber si una región se aloja en RAM o en archivos. Cuando se usan sólo archivos, fije este parámetro en algo como /tmp/apc.XXXXXX (hay que usar exactamente 6 caracteres en las X). Si se desea usar shm_open/mmap al estilo POSIX, incluya la cadena ".shm" en la máscara. Por ejemplo: /apc.shm.XXXXXX. También puede fijarse a "/dev/zero" para usar la interfaz /dev/zero del kernel para usar un mapa anónimo. Si el parámetro no se define, se usa un mapa anónimo.',
    'apc.preload_path' => 'Opcionalmente, si se define esta ruta, APC va a precargar estos archivos en memoria (No aplica en APCu)',
    'apc.rfc1867' => 'Si se compiló APC con PHP 5.2.0 o posterior, está disponible un hook para subida de archivos según el RFC1867. Significa que cualquier subida de archivos que incluye un campo APC_UPLOAD_PROGRESS antes del campo de archivo (en un formulario de subida de archivos) va a crear una entrada en APCu con el mismo nombre que el valor dado a ese campo.',
    'apc.use_request_time'=> 'Usar el tiempo en que se registró el request SAPI como TTL',
    'apc.file_md5'=> 'Guarda un hash md5 de los archivos en caché (no se usa en APCu)',
    'apc.lazy_functions'=> 'Permite lazy loading de funciones (no se cargan hasta que se invocan)',
    'apc.lazy_classes'=> 'Permite lazy loading de clases (no se cargan hasta que se invocan)',
    'apc.rfc1867_prefix'=> 'Prefijo para la llave de caché que se genera cuando un usuario sube un archivo y está activo apc.rfc1867',
    'apc.rfc1867_name'=> 'Especifica el nombre del input que se debe poner en un formulario para activar el progreso de upload de APC upload progress. Este valor se usa también como sufijo en la llave',
    'apc.rfc1867_freq' => 'Frecuencia con que se actualiza el progreso de la subida de un archivo si está activo el apc.rfc1867.',
    'apc.rfc1867_ttl'=> 'TTL para llaves generadas por rfc1867.',
    'apc.localcache'=> 'Esto habilita una copia local del caché, sin bloqueo, que reduce los bloqueos de lectura cuando se está escribiendo al caché.',
    'apc.ttl' => 'Los segundos que una entrada de caché permanece en memoria cuando no es utilizada y otra entrada necesita usar esa memoria. Si se pone este setting en cero, APCu podría llenar el caché con entradas que no se usan, y quedarse sin memoria. Cualquier valor mayor a 0 significa que APCu intentará quitar las entradas obsoletas de la memoria',
    'apc.serializer' => 'Se usa para conectar APCu a un serializador externo.',
    'apc.writable' => '(sin documentación) Suponemos que permite hacer que el caché sea escribible o de sólo lectura.',
    'apc.smart' => '(sin documentación)',
    'apc.slam_defense' => 'Si el servidor tiene mucha carga (o al encender el servicio) podría pasar que muchos procesos quisieran escribir a memoria simultáneamente.  Este parámetro determina el porcentaje de requests que no intentarán escribir al caché. Si se fija en cero se deshabilita la opción.',
    'apc.shm_segments' => 'La cantidad de segmentos de memoria destinados al caché de compilador. Si APC se está quedando sin memoria, pero apc.shm_size es tan alto como el sistema permite, fijar este parámetro podría prevenir que APC se quedara sin memoria.',
    'apc.shm_size' => 'El tamaño de cada segmento de memoria, en MB. Por defecto, algunos sistemas operativos (incluyendo los derivados de BSD), tienen límites muy bajos en el tamaño de cada segmento. (Por eso es necesario destinar N segmentos en vez de un solo segmento grande)'


];
