<?php

$texts = [
    'project.link'                                             => 'Proyecto en GitHub',
    'project.log_in'                                           => 'Entrar',

    'error.not.installed.title'                                => 'Sin instalar',
    'error.not.installed.description'                          => 'Parece que OpCache no está instalado.',
    'error.not.enabled.title'                                  => 'Sin habilitar',
    'error.not.enabled.description'                            => 'Parece que OpCache no está habilitado.',

    'menu.status'                                              => 'Estatus',
    'menu.config'                                              => 'Configuración',
    'menu.scripts'                                             => 'Scripts en caché',
    'menu.graphs'                                              => 'Gráficos',

    'reset.submit'                                             => 'Reiniciar',
    'confirmation.reset'                                       => 'Está seguro de borrar el caché?',
    'confirmation.yes'                                         => 'Sí',
    'confirmation.no'                                          => 'No',

    'status.title'                                             => 'Estatus',
    'status.opcache_enabled'                                   => 'Habilitado',
    'status.cache_full'                                        => 'Caché lleno',
    'status.restart_pending'                                   => 'Reiniciar pendientes',
    'status.restart_in_progress'                               => 'Reiniciar en progreso',

    'memory.title'                                             => 'Uso de memoria',
    'memory.used_memory'                                       => 'Memoria utilizada',
    'memory.free_memory'                                       => 'Memoria libre',
    'memory.wasted_memory'                                     => 'Memoria gastada',
    'memory.current_wasted_percentage'                         => 'Gastada actualmente',

    'stats.title'                                              => 'Estadísticas',
    'stats.num_cached_scripts'                                 => 'Scripts en caché',
    'stats.num_cached_keys'                                    => 'Llaves en caché',
    'stats.max_cached_keys'                                    => 'Máximas llaves en caché',
    'stats.hits'                                               => 'Aciertos',
    'stats.start_time'                                         => 'Tiempo de inicio',
    'stats.last_restart_time'                                  => 'Último reinicio',
    'stats.oom_restarts'                                       => 'Reinicio de Oom',
    'stats.hash_restarts'                                      => 'Reinicio de Hash',
    'stats.manual_restarts'                                    => 'Reinicios manuales',
    'stats.misses'                                             => 'Desaciertos',
    'stats.blacklist_misses'                                   => 'Desaciertos de lista negra',
    'stats.blacklist_miss_ratio'                               => 'Proporción de desaciertos',
    'stats.opcache_hit_rate'                                   => 'Proporción de aciertos de Opcache',

    'config.title'                                             => 'Configuración',
    'config.opcache.enable'                                    => 'Habilitado',
    'config.opcache.enable.description'                        => 'Determina si Zend OPCache está habilitado.',
    'config.opcache.enable_cli'                                => 'Habilitado para CLI',
    'config.opcache.enable_cli.description'                    => 'Determina si Zend OPCache está habilitado para la versión CLI de PHP.',
    'config.opcache.use_cwd'                                   => 'Llaves basadas en directorio actual',
    'config.opcache.use_cwd.description'                       => 'Cuando esta directiva está habilitada, OPcache agrega el directorio actual a la llave del script,eliminando asi posibles problemas por nombres repetidos. El deshabilitar esta opción mejora el rendimiento pero puede afectar aplicaciones existentes.',
    'config.opcache.validate_timestamps'                       => 'Validar timestamps',
    'config.opcache.validate_timestamps.description'           => 'Cuando se deshabilita, debe reiniciar el OPcache manualmente o reiniciar el webserver para ver los cambios en el sistema de archivos',
    'config.opcache.dups_fix'                                  => 'Arreglo de Dups',
    'config.opcache.dups_fix.description'                      => 'Este hack debería estar habilitado para funcionar sólo para evitar errores "Cannot redeclare class".',
    'config.opcache.revalidate_path'                           => 'Revalidar ruta',
    'config.opcache.revalidate_path.description'               => 'Habilita la búsqueda de archivos en la optimización de include_path.',
    'config.opcache.log_verbosity_level'                       => 'Registra nivel de verbosidad',
    'config.opcache.log_verbosity_level.description'           => 'Todos los errores de OPcache van al registro del servidor web. Por default, solo los errores (nivel 0 o 1) son registrados. Usted puede habilitar las advertencias (nivel 2), mensages de información (nivel 3) o de debuggeo (nivel 4).',
    'config.opcache.memory_consumption'                        => 'Tamaño de memoria de Opcache',
    'config.opcache.memory_consumption.description'            => 'El tamaño de la memoria compartida de OPcache.',
    'config.opcache.interned_strings_buffer'                   => 'Cadenas de buffer internadas',
    'config.opcache.interned_strings_buffer.description'       => 'El tamaño de memoria para cadenas internadas en Mbytes.',
    'config.opcache.max_accelerated_files'                     => 'Maximum cached scripts',
    'config.opcache.max_accelerated_files.description'         => 'El número máximo de llaves (scripts) en la tabla de hash The maximum number of keys (scripts) in the OPcache hash table. Only numbers between 200 and 100000 are allowed.',
    'config.opcache.max_wasted_percentage'                     => 'Máximo gastado antes de reiniciar.',
    'config.opcache.max_wasted_percentage.description'         => 'El porcentaje máximo de memoria gastada hasta que se agenda un reinicio.',
    'config.opcache.consistency_checks'                        => 'Frecuencia de chequeos de consistencia',
    'config.opcache.consistency_checks.description'            => 'Revisa el checksum del cache cada N periciones. El valor por default "0" significa que estos chequeos están deshabilitados',
    'config.opcache.force_restart_timeout'                     => 'Obligar timeout de reinicio',
    'config.opcache.force_restart_timeout.description'         => 'Qué tanto esperar (en segundos) para que el reinicio agendado empiece si el caché no está siendo accedido.',
    'config.opcache.revalidate_freq'                           => 'Frecuencia para revisión de cambios',
    'config.opcache.revalidate_freq.description'               => 'Cada cuánto (en seguntos) revisa los timestamps de los archivos por cambios en la asignación de la memoria compartida. "1" significa revisar cada segundo pero sólo una vez por petición. "0" significa siempre validar.',
    'config.opcache.preferred_memory_model'                    => '',
    'config.opcache.preferred_memory_model.description'        => 'Backend de memoria compartida preferida. Dejar vacío si quiere que el sistema decida.',
    'config.opcache.blacklist_filename'                        => 'Lista negra',
    'config.opcache.blacklist_filename.description'            => 'La ubicación de la lista negra de OPcache (wildcards permitidos). Cada lista negra de OPcache es un archivo de texto que contiene los nombres de los archivos que no deben ser acelerados. El formato del archivo es agregar cada nombre de archivo en una nueva línea. El nombre del archivo puede ser la ubicación completa o solo el prefijo del archivo (ej., /var/www/x  pone en la lista negra todos los archivos y directorios en /var/www que empiezan con \'x\'). Las líneas que empiezan con ; son ignoradas (comentarios).',
    'config.opcache.max_file_size'                             => 'Excluir caché de tamaño mayor',
    'config.opcache.max_file_size.description'                 => 'Permite excluir archivos grandes del caché. Por default todos los archivos se incluyen.',
    'config.opcache.error_log'                                 => 'Registro de errores',
    'config.opcache.error_log.description'                     => 'El nombre del error_log de OPcachefile. Las cadenas vacías suponen "stderr".',
    'config.opcache.protect_memory'                            => 'Proteger memoria',
    'config.opcache.protect_memory.description'                => 'Proteger la memoria compartida de escituras inesperadas durante la ejecución de los scripts. Útil para debuggeo interno únicamente.',
    'config.opcache.save_comments'                             => 'Guardar comentarios',
    'config.opcache.save_comments.description'                 => 'Si está deshabilitado, todos los comentarios de PHPDoc son eliminados del código para reducir el tamaño del código optimizado.',
    'config.opcache.fast_shutdown'                             => 'Cierre rápido',
    'config.opcache.fast_shutdown.description'                 => 'Si está habilitado, una secuencia de apagar rápido es usada para acelerar el código.',
    'config.opcache.enable_file_override'                      => 'Sobreescribir el archivo',
    'config.opcache.enable_file_override.description'          => 'Permite sobreescribir la existencia de archivos (file_exists, etc.).',
    'config.opcache.optimization_level'                        => 'Nivel de optimización',
    'config.opcache.optimization_level.description'            => 'Es una máscara de bits donde cada bit habilita o deshabilita los pases de OPcache.',
    'config.opcache.mmap_base'                                 => 'Mmap base',
    'config.opcache.mmap_base.description'                     => 'La base usada para los segmentos de memoria compartida en Windows. Todos los procesos PHP deben mapear la memoria compartida con el mismo espacio de direcciones. Utilizando esta directiva se corrigen los errores "Unable to reattach to base address".',
    'config.opcache.restrict_api'                              => 'Restrict API',
    'config.opcache.restrict_api.description'                  => 'Permite llamar a funciones de la API de OPcache solamente desde scripts de PHP cuya ruta comience con la cadena especificada. El valor predeterminado de "" significa sin restricciones.',
    'config.opcache.file_update_protection'                    => 'File update protection',
    'config.opcache.file_update_protection.description'        => 'Prevents caching files that are less than this number of seconds old. It protects from caching of incompletely updated files. In case all file updates on your site are atomic, you may increase performance by setting it to "0".',
    'config.opcache.huge_code_pages'                           => 'Huge code pages',
    'config.opcache.huge_code_pages.description'               => 'Enables or disables copying of PHP code (text segment) into HUGE PAGES. This should improve performance, but requires appropriate OS configuration.',
    'config.opcache.lockfile_path'                             => 'Lockfile path',
    'config.opcache.lockfile_path.description'                 => 'Absolute path used to store shared lockfiles (for *nix only)',
    'config.opcache.file_cache'                                => 'File cache',
    'config.opcache.file_cache.description'                    => 'Enables and sets the second level cache directory. It should improve performance when SHM memory is full, at server restart or SHM reset. The default "" disables file based caching.',
    'config.opcache.file_cache_only'                           => 'File cache only',
    'config.opcache.file_cache_only.description'               => 'Enables or disables opcode caching in shared memory.',
    'config.opcache.file_cache_consistency_checks'             => 'File cache consistency checks',
    'config.opcache.file_cache_consistency_checks.description' => 'Enables or disables checksum validation when script loaded from file cache.',
    'config.opcache.file_cache_fallback'                       => 'File cache fallback',
    'config.opcache.file_cache_fallback.description'           => 'Implies opcache.file_cache_only=1 for a certain process that failed to reattach to the shared memory (for Windows only). Explicitly enabled file cache is required.',
    'config.opcache.validate_permission'                       => 'Validate permission',
    'config.opcache.validate_permission.description'           => 'Validates the cached file permissions against the current user.',
    'config.opcache.validate_root'                             => 'Validate root',
    'config.opcache.validate_root.description'                 => 'Prevents name collisions in chroot\'ed environments. This should be enabled in all chroot\'ed environments to prevent access to files outside the chroot.',

    'blacklist.title'                                          => 'Lista negra',
    'blacklist.empty'                                          => 'La lista negra está vacía.',

    'scripts.title'                                            => 'Scripts en caché',
    'scripts.overview.title'                                   => 'Resumen',
    'scripts.empty'                                            => 'Ningún script está en caché',
    'scripts.directory.script_count'                           => ' (<i class="count">%s</i> archivos)',
    'scripts.full_path'                                        => 'Nombre del archivo',
    'scripts.hits'                                             => 'Aciertos',
    'scripts.memory_consumption'                               => 'Memoria',
    'scripts.last_used_timestamp'                              => 'Último usado',
    'scripts.timestamp'                                        => 'Creado',
    'scripts.actions'                                          => 'Acciones',
    'script.invalidate'                                        => 'Invalidar',
    'scripts.filter.placeholder'                               => 'Filtrar scripts en caché',

    'graph.title'                                              => 'Gráficos',
    'graph.memory.title'                                       => 'Memoria',
    'graph.memory.free'                                        => 'libre',
    'graph.memory.used'                                        => 'usada',
    'graph.memory.wasted'                                      => 'gastada',
    'graph.keys.title'                                         => 'Llaves',
    'graph.keys.free'                                          => 'libres',
    'graph.keys.scripts'                                       => 'usadas',
    'graph.keys.wasted'                                        => 'gastadas',
    'graph.hits.title'                                         => 'Aciertos',
    'graph.hits.hits'                                          => 'aciertos',
    'graph.hits.misses'                                        => 'desaciertos',
    'graph.hits.blacklist'                                     => 'lista negra'
];
