<?php

$texts = [
    'project.link'                                          => 'Progetto su GitHub',
    'project.log_in'                                        => 'Accedi',

    'error.not.installed.title'                             => 'Non installato',
    'error.not.installed.description'                       => 'Sembra che OPCache non sia installato.',
    'error.not.enabled.title'                               => 'Non abilitato',
    'error.not.enabled.description'                         => 'Sembra che OPCache non sia abilitato.',

    'menu.status'                                           => 'Stato',
    'menu.config'                                           => 'Configurazione',
    'menu.scripts'                                          => 'Script nella cache',
    'menu.graphs'                                           => 'Grafici',

    'reset.submit'                                          => 'Azzera',
    'confirmation.reset'                                    => 'Sei sicuro di voler azzerare le statistiche?',
    'confirmation.yes'                                      => 'Sì',
    'confirmation.no'                                       => 'No',

    'status.title'                                          => 'Stato',
    'status.opcache_enabled'                                => 'Abilitato',
    'status.cache_full'                                     => 'Cache satura',
    'status.restart_pending'                                => 'Riavvio in attesa',
    'status.restart_in_progress'                            => 'Riavvio in corso',

    'memory.title'                                          => 'Utilizzo memoria',
    'memory.used_memory'                                    => 'Memoria utilizzata',
    'memory.free_memory'                                    => 'Memoria libera',
    'memory.wasted_memory'                                  => 'Memoria sprecata',
    'memory.current_wasted_percentage'                      => 'Memoria attualmente sprecata',

    'stats.title'                                           => 'Statistiche',
    'stats.num_cached_scripts'                              => 'Tot. script nella cache',
    'stats.num_cached_keys'                                 => 'Tot. key nella cache',
    'stats.max_cached_keys'                                 => 'Tot. key consentite nella cache',
    'stats.hits'                                            => 'Successi',
    'stats.start_time'                                      => 'Data/ora di avvio',
    'stats.last_restart_time'                               => 'Data/ora ultimo riavvio',
    'stats.oom_restarts'                                    => 'Tot. riavvii Oom',
    'stats.hash_restarts'                                   => 'Tot. riavvii Hash',
    'stats.manual_restarts'                                 => 'Tot. riavvii manuali',
    'stats.misses'                                          => 'Saltati',
    'stats.blacklist_misses'                                => 'Saltati in base a blacklist',
    'stats.blacklist_miss_ratio'                            => 'Percentuale saltati',
    'stats.opcache_hit_rate'                                => 'OPCache percentuale successi',

    'config.title'                                          => 'Configurazione',
    'config.opcache.enable'                                 => 'Abilitato',
    'config.opcache.enable.description'                     => 'Determina se Zend OPCache è abilitata.',
    'config.opcache.enable_cli'                             => 'Abilita per CLI',
    'config.opcache.enable_cli.description'                 => 'Determina se Zend OPCache è abilitata per la versione CLI di PHP.',
    'config.opcache.use_cwd'                                => 'Usa spazio di nomi per le key',
    'config.opcache.use_cwd.description'                    => 'Quando questa direttiva è abilitata, OPCache utilizza la directory di lavoro corrente (CWD) come namespace delle key. Disabilitare questa direttiva migliora le prestazioni, ma può corrompere applicazioni esistenti.',
    'config.opcache.validate_timestamps'                    => 'Valida i timestamp',
    'config.opcache.validate_timestamps.description'        => 'Quando disabilitata, dovrai invalidare la cache manualmente (o riavviare il webserver) per applicare i cambiamenti. Quando abilitata, i cambiamenti verranno rilevati automaticamente.',
    'config.opcache.inherited_hack'                         => 'Inherited hack', // ???
    'config.opcache.inherited_hack.description'             => '',
    'config.opcache.dups_fix'                               => 'Dups fix', // ???
    'config.opcache.dups_fix.description'                   => '',
    'config.opcache.revalidate_path'                        => 'Ri-valida percorsi',
    'config.opcache.revalidate_path.description'            => 'Abilita o disabilita l\'ottimizzazione per i file cercati nella "include_path".',
    'config.opcache.log_verbosity_level'                    => 'Accuratezza dei Log',
    'config.opcache.log_verbosity_level.description'        => 'Tutti gli errori di OPCache sono scritti nel log del webserver. Di default solo gli errori fatali (livello 0) o gli errori (livello 1) sono loggati. Puoi anche abilitare gli avvertimenti (livello 3) o i messaggi di debug (livello 4).',
    'config.opcache.memory_consumption'                     => 'Memoria massima',
    'config.opcache.memory_consumption.description'         => 'La memoria massima condivisa utilizzabile da OPCache.',
    'config.opcache.interned_strings_buffer'                => 'Memoria massima stringhe internate',
    'config.opcache.interned_strings_buffer.description'    => 'La memoria massima in MB utilizzabile dal buffer delle stringhe internate.',
    'config.opcache.max_accelerated_files'                  => 'Tot. massimo dei file inseribili nella cache',
    'config.opcache.max_accelerated_files.description'      => 'Il totale massimo degli script inseribili nella cache. Solo numeri tra 200 e 100000 sono consentiti.',
    'config.opcache.max_wasted_percentage'                  => 'Limite memoria sprecata',
    'config.opcache.max_wasted_percentage.description'      => 'La percentuale massima di memoria sprecata prima che un riavvio sia automaticamente programmato.',
    'config.opcache.consistency_checks'                     => 'Frequenza controlli di coerenza',
    'config.opcache.consistency_checks.description'         => 'Controlla i checksum della cache ogni TOT richieste. Se "0" il controllo è disabilitato.',
    'config.opcache.force_restart_timeout'                  => 'Tempo di riavvio automatico se la cache non è letta',
    'config.opcache.force_restart_timeout.description'      => 'Quanto tempo aspettare (in secondi) per riavviare automaticamente se la cache non è letta.',
    'config.opcache.revalidate_freq'                        => 'Frequenza rilevamento cambiamenti',
    'config.opcache.revalidate_freq.description'            => 'Quanto frequentemente (in secondi) i timestamp dei file verranno ricontrollati per rilevarne i cambiamenti. "1" significa ricontrolla una volta al secondo, ma una sola volta per richiesta. "0" significa ricontrolla sempre.',
    'config.opcache.preferred_memory_model'                 => '',
    'config.opcache.preferred_memory_model.description'     => 'Modello della memoria preferito. Lasciare vuoto per far decidere al sistema.',
    'config.opcache.blacklist_filename'                     => 'Nome del file della blacklist',
    'config.opcache.blacklist_filename.description'         => 'Il percorso del file della blacklist (wildcard * è consentito). Ogni file consiste in una lista di percorsi che devono essere esclusi dalla cache, un percorso per linea. Il percorso può essere un percorso completo o solo un prefisso; ad esempio "/var/www/x" blocca tutti i file e cartelle in /var/www che iniziano per la lettera "x". Le righe che iniziano per ; verranno ignorate (commenti).',
    'config.opcache.max_file_size'                          => 'Dimensione massima dei file inseribili nella cache',
    'config.opcache.max_file_size.description'              => 'Esclude dalla cache i file più grandi del valore specificato. Se zero il filtro non viene applicato e pertanto ogni file verrà inserito nella cache.',
    'config.opcache.error_log'                              => 'Log degli errori',
    'config.opcache.error_log.description'                  => 'Il nome del file contenente i log di OPcache. Se vuoto utilizza "stderr".',
    'config.opcache.protect_memory'                         => 'Proteggi memoria',
    'config.opcache.protect_memory.description'             => 'Protegge la memoria condivisa dalla scrittura accidentale durante l\'esecuzione degli script. Utile per il debug di OPCache.',
    'config.opcache.save_comments'                          => 'Preserva i commenti',
    'config.opcache.save_comments.description'              => 'Se disabilitato i PHPDoc verranno eliminati dal codice per ridurre la dimensione dei file ottimizzati.',
    'config.opcache.load_comments'                          => 'Load comments',
    'config.opcache.load_comments.description'              => 'Se disabilitato, i commenti PHPDoc non sono caricati dalla memoria condivisa. Se si è deciso di preservare i commenti solo per alcune applicazioni, se abilitato, consente ad altre applicazioni (che non ne hanno bisogno) di non caricarli.',
    'config.opcache.fast_shutdown'                          => 'Spegnimento veloce',
    'config.opcache.fast_shutdown.description'              => 'Se abilitato, lo spegnimento veloce è abilitato per il codice accelerato.',
    'config.opcache.enable_file_override'                   => 'Ottimizza funzioni file',
    'config.opcache.enable_file_override.description'       => 'Ridefinisce la funzione "file_exists()" e simili per migliori prestazioni.',
    'config.opcache.optimization_level'                     => 'Livello di ottimizzazione',
    'config.opcache.optimization_level.description'         => 'Una bitmask dove ogni bit abilita o disabilita i relativi passaggi della OPCache.',

    'blacklist.title'                                       => 'Lista nera',
    'blacklist.empty'                                       => 'Nessuno script è in lista nera',

    'scripts.title'                                         => 'Script nella cache',
    'scripts.overview.title'                                => 'Riepilogo',
    'scripts.empty'                                         => 'Nessuno script è nella cache',
    'scripts.directory.script_count'                        => ' (<i class="count">%s</i> file)',
    'scripts.full_path'                                     => 'Nome file',
    'scripts.hits'                                          => 'Accessi',
    'scripts.memory_consumption'                            => 'Memoria',
    'scripts.last_used_timestamp'                           => 'Ultimo utilizzo',
    'scripts.timestamp'                                     => 'Creazione',
    'scripts.actions'                                       => 'Azioni',
    'script.invalidate'                                     => 'Invalida',
    'scripts.filter.placeholder'                            => 'Filtra script nella cache',

    'graph.title'                                           => 'Grafici',
    'graph.memory.title'                                    => 'Memoria',
    'graph.memory.free'                                     => 'libera',
    'graph.memory.used'                                     => 'usata',
    'graph.memory.wasted'                                   => 'sprecata',
    'graph.keys.title'                                      => 'Key',
    'graph.keys.free'                                       => 'libere',
    'graph.keys.scripts'                                    => 'usate',
    'graph.keys.wasted'                                     => 'sprecate',
    'graph.hits.title'                                      => 'Accessi',
    'graph.hits.hits'                                       => 'accessi',
    'graph.hits.misses'                                     => 'mancati',
    'graph.hits.blacklist'                                  => 'lista nera'
];
