<?php

$texts = [
    'project.link'                                          => 'Projeto no GitHub',
    'project.log_in'                                        => 'Efetuar Login',

    'error.not.installed.title'                             => 'Não instalada',
    'error.not.installed.description'                       => 'A extensão OpCache não está instalada.',
    'error.not.enabled.title'                               => 'Não habilitada',
    'error.not.enabled.description'                         => 'A extensão Opcache não está habilitada.',

    'menu.status'                                           => 'Status',
    'menu.config'                                           => 'Configuração',
    'menu.scripts'                                          => 'Scripts em Cache',
    'menu.graphs'                                           => 'Gráficos',

    'reset.submit'                                          => 'Reiniciar',
    'confirmation.reset'                                    => 'Você tem certeza que quer reiniciar o cache?',
    'confirmation.yes'                                      => 'Sim',
    'confirmation.no'                                       => 'Não',

    'status.title'                                          => 'Status',
    'status.opcache_enabled'                                => 'Habilitado',
    'status.cache_full'                                     => 'Cache cheio',
    'status.restart_pending'                                => 'Reinicio pendente',
    'status.restart_in_progress'                            => 'Reinicio em progresso',

    'memory.title'                                          => 'Uso da memória',
    'memory.used_memory'                                    => 'Memória usada',
    'memory.free_memory'                                    => 'Memória livre',
    'memory.wasted_memory'                                  => 'Memória desperdiçada',
    'memory.current_wasted_percentage'                      => 'Atualmente desperdiçada',

    'stats.title'                                           => 'Estatísticas',
    'stats.num_cached_scripts'                              => 'Scripts em Cache',
    'stats.num_cached_keys'                                 => 'Chaves em cache',
    'stats.max_cached_keys'                                 => 'Máximas chaves em cache',
    'stats.hits'                                            => 'Acessos',
    'stats.start_time'                                      => 'Data de início',
    'stats.last_restart_time'                               => 'Última reinício',
    'stats.oom_restarts'                                    => 'Reinícios de Oom',
    'stats.hash_restarts'                                   => 'Reinícios de hash',
    'stats.manual_restarts'                                 => 'Reinícios manuais',
    'stats.misses'                                          => 'Desacertos',
    'stats.blacklist_misses'                                => 'Desacertos da blacklist',
    'stats.blacklist_miss_ratio'                            => 'Proporção de desacertos',
    'stats.opcache_hit_rate'                                => 'Proporção de acertos do Opcache',

    'config.title'                                          => 'Configuração',
    'config.opcache.enable'                                 => 'Habilitado',
    'config.opcache.enable.description'                     => 'Determina se Zend OPCache está habilitada.',
    'config.opcache.enable_cli'                             => 'Habilitado para CLI',
    'config.opcache.enable_cli.description'                 => 'Determina se Zend OPCache está habilitado para a versão CLI do PHP.',
    'config.opcache.use_cwd'                                => 'Chaves baseadas no diretório atual',
    'config.opcache.use_cwd.description'                    => 'Quando esta diretiva está habilitada, OPcache acrescentará o diretório atual à chave do script, assim eliminando possíveis colisões entre arquivos com o mesmo nome. Desabilitando esta diretiva melhora o desempenho, mas pode causar falhas em aplicações existentes.',
    'config.opcache.validate_timestamps'                    => 'Validar timestamps',
    'config.opcache.validate_timestamps.description'        => 'Quando desabilitado, você precisa reiniciar o OPcache manualmente ou reiniciar o servidor web para que as modificações no sistema de arquivos tenham efeito.',
    'config.opcache.inherited_hack'                         => 'Hack de herança',
    'config.opcache.inherited_hack.description'             => '',
    'config.opcache.dups_fix'                               => 'Correções de duplicação',
    'config.opcache.dups_fix.description'                   => '',
    'config.opcache.revalidate_path'                        => 'Revalidar caminho',
    'config.opcache.revalidate_path.description'            => 'Habilita ou desabilita a otimização na busca de arquivos no include_path.',
    'config.opcache.log_verbosity_level'                    => 'Nível de verbosidade do log',
    'config.opcache.log_verbosity_level.description'        => 'Todos os erros do OPcache são enviados para o log do servidor web. Por padrão, apenas erros fatais (nível 0) ou erros normais (nível 1) são registrados. Você pode habilitar advertências (nível 2), mensagens de informação (nível 3) ou mensagens de depuração (nível 4).',
    'config.opcache.memory_consumption'                     => 'Tamanho da memória do Opcache',
    'config.opcache.memory_consumption.description'         => 'O tamanho memória compartilhada do OPcache.',
    'config.opcache.interned_strings_buffer'                => 'Tamanho da memória para strings internadas.',
    'config.opcache.interned_strings_buffer.description'    => 'O tamanho da memória para as strings internadas, em Mbytes.',
    'config.opcache.max_accelerated_files'                  => 'Scripts máximo em cache',
    'config.opcache.max_accelerated_files.description'      => 'O número máximo de chaves (scripts) na tabela de hash do OPcache. Apenas números entre 200 e 100000 são permitidos.',
    'config.opcache.max_wasted_percentage'                  => 'Desperdício máximo antes de um reinício.',
    'config.opcache.max_wasted_percentage.description'      => 'A porcentagem máxima de memória "desperdiçada" para que ocorra o agendamento de um reinício.',
    'config.opcache.consistency_checks'                     => 'Frequência de verificação de concistência.',
    'config.opcache.consistency_checks.description'         => 'Verificar a integridade do cache a cada N requisições. O valor padrão de "0" significa que a verificação está desabilitada.',
    'config.opcache.force_restart_timeout'                  => 'Forçar reinício no tempo limite',
    'config.opcache.force_restart_timeout.description'      => 'Quanto tempo esperar (em segundos) para iniciar um reinício agendado caso o cache não esteja sendo acessado.',
    'config.opcache.revalidate_freq'                        => 'Frequência para verificar por mudanças',
    'config.opcache.revalidate_freq.description'            => 'Frequência (em segundos) para se verificar por mudanças nos arquivos da alocação de memória compartilhada. "0" significa verificar à cada requisição.',
    'config.opcache.preferred_memory_model'                 => '',
    'config.opcache.preferred_memory_model.description'     => 'Back-end de memória compartilhada. Deixe em branco para deixar o sistema decidir.',
    'config.opcache.blacklist_filename'                     => 'Blacklist',
    'config.opcache.blacklist_filename.description'         => 'Localização do arquivo de blacklist (valores curinga são permitidos). Cada arquivo de blacklist do OPcache é um arquivo de texto que possui o nome dos arquivos que não devem ser otimizados. O formato do arquivo é uma linha pra cada arquivo a ser ignorado. O nome do arquivo pode ser o caminho completo ou apenas um prefixo (ex: /var/www/x irá ignorar todos os arquivos e diretórios em /var/www que comecem com "x"). Linhas começando com ; são ignorados (comentários).',
    'config.opcache.max_file_size'                          => 'Desabilitar cache de arquivos com tamanho maior que',
    'config.opcache.max_file_size.description'              => 'Habilitar exclusão de arquivos grandes de serem adicionados ao cache. Por padrão todos os arquivos são armazenados em cache.',
    'config.opcache.error_log'                              => 'Log de erros',
    'config.opcache.error_log.description'                  => 'Arquivo error_log do OPcache. String vazia significa "stderr".',
    'config.opcache.protect_memory'                         => 'Proteger memória',
    'config.opcache.protect_memory.description'             => 'Protege a memória compartilhada de escrita inesperada durante a execução do script. Útil apenas para depuração interna.',
    'config.opcache.save_comments'                          => 'Manter comentários',
    'config.opcache.save_comments.description'              => 'Se desabilitado, todos os comentários PHPDoc serão removidos do código para diminuir o tamanho do código otimizado.',
    'config.opcache.load_comments'                          => 'Carregar comentários',
    'config.opcache.load_comments.description'              => 'Se desabilitado, comentários PHPDoc não serão carregados do cache mesmo que eles existam.',
    'config.opcache.fast_shutdown'                          => 'Desligamento rápido',
    'config.opcache.fast_shutdown.description'              => 'Se habilitado, uma sequência rápida de desligamento é utilizada para acelerar a execução do código',
    'config.opcache.enable_file_override'                   => 'Sobreposição de arquivo',
    'config.opcache.enable_file_override.description'       => 'Habilita a funcionalidade de otimização a partir da sobreposição da existência de arquivos (file_exists, etc.).',
    'config.opcache.optimization_level'                     => 'Nível de otimização',
    'config.opcache.optimization_level.description'         => 'Uma bitmask, na qual cada bit habilita ou desabilita os apropriados passos do OPcache.',

    'blacklist.title'                                       => 'Blacklist',
    'blacklist.empty'                                       => 'Nenhum script adicionado a blacklisted',

    'scripts.title'                                         => 'Scripts em Cache',
    'scripts.overview.title'                                => 'Visão Geral',
    'scripts.empty'                                         => 'Nenhum script em cache',
    'scripts.directory.script_count'                        => ' (<i class="count">%s</i> arquivos)',
    'scripts.full_path'                                     => 'Nome do arquivo',
    'scripts.hits'                                          => 'Acessos',
    'scripts.memory_consumption'                            => 'Memória',
    'scripts.last_used_timestamp'                           => 'Último uso',
    'scripts.timestamp'                                     => 'Criado em',
    'scripts.actions'                                       => 'Ações',
    'script.invalidate'                                     => 'Invalidar',
    'scripts.filter.placeholder'                            => 'Filtrar scripts em cache',

    'graph.title'                                           => 'Gráficos',
    'graph.memory.title'                                    => 'Memória',
    'graph.memory.free'                                     => 'livre',
    'graph.memory.used'                                     => 'usada',
    'graph.memory.wasted'                                   => 'desperdiçada',
    'graph.keys.title'                                      => 'Chaves',
    'graph.keys.free'                                       => 'livre',
    'graph.keys.scripts'                                    => 'usada',
    'graph.keys.wasted'                                     => 'desperdiçada',
    'graph.hits.title'                                      => 'Acessos',
    'graph.hits.hits'                                       => 'acessos',
    'graph.hits.misses'                                     => 'desacertos',
    'graph.hits.blacklist'                                  => 'blacklist'
];
